Experimental: Unify NamingSchemes.
PyCQA/pylint pull request #3704
Opened 2020-06-21 07:42 UTC by bukzor

## Description

The current default pylint naming schemes only differ on three parameters:

 1. characters allowed at beginning of name
 2. characters allowed elsewhere
 3. minimum length of name

Where this was not true was due to either bugs, oversight, or legacy
inertia; i's hard for me to tell the difference.  Many odd
discrepancies among the naming schemes have been rectified, and this
change will bother users by calling out some of their bizarre naming
conventions, but all such issues are valid.

For churn considerations, I've not (yet?) modified the names of the
naming scheme objects although they've transitioned from being classes
to objects, and there's a couple other bits of odd naming in here for
the same reason. My aim was chiefly to show that this was possible, and
spur consideration of the idea.

A further improvement would be to set a "minimum length" for names in
the configuration, which should be checked apart from "naming scheme"
issues. This would greatly reduce the need for users to read and
understand regular expressions, and will make messages more actionable,
but also separating that additional resonsibility would further simplify
and rectify the naming schemes.

## Type of Changes
|   | Type |
| ------------- | ------------- |
|    | :bug: Bug fix  |
|    | :sparkles: New feature |
| ✓  | :hammer: Refactoring  |
|    | :scroll: Docs |

2020-06-21 08:24 UTC, bukzor commented
I don't understand these test failures. I'm unable to reproduce them reliably, and I notice they only happen when I run the whole test suite -- the tests alone don't fail. I also see that I sometimes get the same errors in master branch. Are there currently flaky tests in master?

2021-01-04 18:29 UTC, hippo91 requested changes
@bukzor thanks a lot for this PR and sorry for the delay.
It is clearly an improvement in our naming scheme management.
However i'm a bit confused by the fact that, at this point, this PR prevents the user to use variable with only one character in its name...
By the way, i would like to have @PCManticore on this topic.

2021-01-04 18:29 UTC, hippo91 commented on tests/extensions/data/compare_to_zero.py
> +# pylint: disable=literal-comparison,missing-docstring,misplaced-comparison-constant,invalid-name
I find a little bit damageable if `pylint` is not compatible with constant name that are one letter long.
What do you think about it?

2021-01-04 18:29 UTC, hippo91 commented on tests/messages/func_w0801.txt
> +==input.w0801_same:4
Why is this change needed?

2021-01-04 18:29 UTC, hippo91 commented on tests/functional/u/undefined_variable.rc
> +good-names=i,j,k,ex,Run,_,_dt
Once again i think it is very risky to forbid using single character named variable...

2022-04-01 21:06 UTC, DanielNoord commented
I'm going to close this PR as it has become stale.

I looked at the changes this PR would introduce and have decided not to take them further myself. I think a real contribution would be finding a way to do the naming styles without having to compile 25+ regex patterns, but I'm not sure if that is even feasible.

2022-04-01 21:06 UTC, closed without merging

2022-08-11 14:31 UTC, bukzor commented on ChangeLog
> +   3. override the default regexen, via pylintrc (not recommended)
It's not recommended because even for those deeply familiar with regex (few) it is much too easy to make regex with unintended matches / exclusions.

2022-08-11 14:32 UTC, bukzor commented on pylint/checkers/base.py
> +        self.head_exclude = head_exclude
Yes, exactly. As in head and tail of a snake -- the tail is everything but the head.

2022-08-11 14:42 UTC, bukzor commented
I intend to revive this work -- after a long haitus, I'm once again participaing in the open-source community.

Please advise:
 1. Would you prefer I update this PR or start a fresh one?
 2. Are there any of these changes that should be excluded?

2022-08-11 14:52 UTC, DanielNoord commented
> I intend to revive this work -- after a long haitus, I'm once again participaing in the open-source community.

Welcome back! 😄 

> Please advise:
> 
> 1. Would you prefer I update this PR or start a fresh one?
> 2. Are there any of these changes that should be excluded?

I think a fresh one is probably better since many of the files here have now moved or significantly changed.

That said, I know there was some discussion about whether we should pursue the changes in this PR. I'm still sympathetic to simplifying this code, but I'm not sure how feasible the current approach still is.
We have now also have types that are only part of a specific style and are not defined on other styles, such as `TypeVar`.

2022-08-11 15:17 UTC, bukzor commented on pytest.ini
> +addopts=-m "not acceptance" --tb=short
I notice this has been done without me, in the intervening time.

2022-08-11 15:18 UTC, bukzor commented on tests/conftest.py
> +
I notice this has been done without me, in the intervening time.

2022-08-11 15:18 UTC, bukzor commented on tests/conftest.py
> +    os.environ["PYLINTRC"] = PYLINTRC
I notice this has been done without me, in the intervening time.

2022-08-11 15:31 UTC, bukzor commented
> > I intend to revive this work -- after a long haitus, I'm once again participaing in the open-source community.
> 
> Welcome back! 😄

Thank you!

> > Please advise:
> > 
> > 1. Would you prefer I update this PR or start a fresh one?
> > 2. Are there any of these changes that should be excluded?
> 
> I think a fresh one is probably better since many of the files here have now moved or significantly changed.

Roger.

> That said, I know there was some discussion about whether we should pursue the changes in this PR. I'm still sympathetic to simplifying this code, but I'm not sure how feasible the current approach still is. We have now also have types that are only part of a specific style and are not defined on other styles, such as `TypeVar`.

I'm aware that the approach taken isn't strictly agreeable, but I do believe the goals are still relevant and attainable. Once I have something worth discussing I'll bother you again.  Async text (i.e. github issues) isn't very conducive to debating abstract ideas such as hypothetical implementations, especially between strangers. How do you normally handle such complex communications?

2022-08-11 15:33 UTC, DanielNoord commented
> I'm aware that the approach taken isn't strictly agreeable, but I do believe the goals are still relevant and attainable. Once I have something worth discussing I'll bother you again. Async text (i.e. github issues) isn't very conducive to debating abstract ideas such as hypothetical implementations, especially between strangers. How do you normally handle such complex communications?

Normally we use issues to discuss significant proposals of change. It's not really perfect like you said, but it also helps narrow the scope of PRs which greatly helps with reviewing them. If the discussion in a PR is becoming too long it is often a good indication that it might try to do too much in one PR.

2022-08-11 16:02 UTC, Pierre-Sassoulas commented
Hello @bukzor and welcome back !

(I started to work on this issue myself and lost the code some time ago so I had some ideas about it)

I think short variable name should be correctly checked as per hippo's comment. Also imo a split between a new check for variable names that are too small and variable names not respecting the name convention is required (using old_names so retro compatibility for all messages disabled with 'invalid-name' previousely are still disabled for both new message).

We usually use async text communication for everything as we're in various timezones and pylint is something I do on my free time / when convenient. So I don't want to schedule a call unless absolutely necessary. But I think it's possible to talk about the required steps and do them one by one with issues as Daniel said though.

2022-08-11 23:45 UTC, bukzor commented
> Hello @bukzor and welcome back !

Thank you :D

> I think short variable name should be correctly checked as per hippo's comment.

Please expand on "correctly" here? My best guess is that you mean: One-character variables should be admitted by the name checker without error, by default.

> Also imo a split between a new check for variable names that are too small and variable names not respecting the name convention is required ...

To clarify, you're advocating a split of the existing `NameChecker` into two new checkers? One for naming style, and one for naming length. The naming-style checker would disregard any length problems.

If so, my goal would be to add the two new checkers in a disabled-by-default state until you're ready, while leaving the old checker untouched, for now.

>  ... (using old_names so retro compatibility for all messages disabled with 'invalid-name' previousely are still disabled for both new message).

I don't understand this bit. What is `old_names`? Do you mean that there would be two new error names that would be set to also disable themselves with disablement of `invalid-name`? I didn't know that was a feature of checkers.

> We usually use async text communication for everything as we're in various timezones and pylint is something I do on my free time / when convenient. So I don't want to schedule a call unless absolutely necessary. But I think it's possible to talk about the required steps and do them one by one with issues as Daniel said though.

Got it! I will endevour to adopt this workflow. Thank you for including me :)

2022-08-13 09:59 UTC, Pierre-Sassoulas commented
> Please expand on "correctly" here? My best guess is that you mean: One-character variables should be admitted by the name checker without error, by default.

I was thinking that a name that is in the list of accepted name should be ok for both checks.

``ab`` should be valid snake case but too short, and that ``aB`` should be invalid and too short, ``Ab`` should be valid PascalCase, but not ``ab``, etc.. We would also have to define what we want for one letter name. i.e. ``A`` and ``a``, is ``A`` Pascalcase or uppercase with underscore ? is ``a`` camelCase or snake_case ? Maybe both ?

| snake_case name |       A      |  a |     Ab      |  ab |      Abcd |  abcd |
|----------|:-------------:|------:|:-------------:|------:|:-------------:|------:|
| invalid-name | yes | no | yes | no | yes | no |
| name-too-short |   yes | yes |  yes |   yes | no | no |

I realize that if we keep regex this is going to be hell so maybe no invalid name for name that are too short **when the regex used is the default one** (maybe someone crafted a masterful regex that handle short names properly somewhere) is acceptable:

| snake_case name |       A      |  a |     Ab      |  ab |      Abcd |  abcd |
|----------|:-------------:|------:|:-------------:|------:|:-------------:|------:|
| invalid-name | no | no |  no | no | yes | no |
| name-too-short | yes |   yes |   yes |   yes | no | no |

> To clarify, you're advocating a split of the existing NameChecker into two new checkers? One for naming style, and one for naming length. The naming-style checker would disregard any length problems.

I think depending on what we decide for the problem above having one checker instead of two could be simpler but yes.

> If so, my goal would be to add the two new checkers in a disabled-by-default state until you're ready, while leaving the old checker untouched, for now.

That could work well but add complexity, if we can refactor the existing checker it's probably less work overall. How would you do the change to the TypeVar check @DanielNoord ? Would a standalone checker with only TypeVar work ? Should we keep TypeVar "generic" ?

>  Do you mean that there would be two new error names that would be set to also disable themselves with disablement of invalid-name?

Yes, check this code: https://github.com/PyCQA/pylint/blob/main/pylint/checkers/base/docstring_checker.py#L64 
Result here, it's possible to enable ``missing-function-docstring`` by using the old name : https://github.com/PyCQA/pylint/blob/main/tests/functional/u/use/use_symbolic_message_instead.py#L20