Fix Link
PyCQA/pylint pull request #3908
Opened 2020-10-19 14:37 UTC by jss367

The link to IDE integration didn't work for me so I found what seems to be the right link and added it.

## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [ ] Write a good description on what the PR does.

## Description

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :scroll: Docs |

## Related Issue

2020-10-30 13:02 UTC, hippo91 requested changes
@jss367 thanks for submitting this PR. However i don't understand the need.
When visiting the following address: http://pylint.pycqa.org/en/2.6/faq.html the link seems to be functional.

2020-10-30 13:02 UTC, hippo91 commented on doc/faq.rst
> +Much probably. Read http://pylint.pycqa.org/en/latest/user_guide/ide-integration.html
This link is not a `reStructuredText` link. By the way the original link seems to be correct.

2020-10-30 23:40 UTC, jss367 commented
@hippo91 Maybe I'm editing the wrong page. When I go to https://docs.pylint.org/en/1.6.0/faq.html and click on the link I get this error:

![image](https://user-images.githubusercontent.com/3067731/97765195-9553d980-1ae7-11eb-8aa8-72d358e32b99.png)

I was trying to fix that.

2020-11-26 09:33 UTC, hippo91 commented
@jss367 the link is indeed broken, as all other links constructed with the `ref` keyword. Moreover when building doc locally (running `python -m tox -edocs` everything is fine and the link is not broken. I don't think the solution is to hard code the broken links however i have no idea where this bug may come from.

2020-11-26 10:14 UTC, hippo91 commented
@jss367 i'm sorry but i just realized that you were looking at a very old version doc. Please use https://pylint.pycqa.org/ instead. All the links seem to be ok in it.

2020-11-26 10:14 UTC, closed without merging