Fix column metadata on backslash lint checks
PyCQA/pylint pull request #4003
Opened 2020-12-31 18:58 UTC by msuozzo

The existing logic does not account for the start-of-line to start-of-string offset.

## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [X] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [X] Write a good description on what the PR does.

## Description

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
|  | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |

## Related Issue

2021-01-01 15:18 UTC, Pierre-Sassoulas requested changes
Thank you for the merge request ! Could you also add an example of code that was failing before this change in `tests/functional` so we do not regress later ?

2021-01-03 07:17 UTC, msuozzo commented
Alright added some tests and added a fix to the line metadata to this PR.

There is currently no functional test facility for column but this should be feasible to add. Considering that this would mean modifying all existing functional tests, I think it's best left for a follow-on change.

2021-01-03 21:50 UTC, msuozzo commented
Cleaned up commit history, as well.

2021-01-03 22:11 UTC, Pierre-Sassoulas commented
Wow, you're right the functional test do not check for column ! Well, I made the required change so you can implement this properly : we'll move the legacy backlash functional test to the new functional test framework in : #4012. Also, we're going to add this column check to functional tests in #4013.  Feel free to review them as this will impact what you do here :)

2021-01-03 23:00 UTC, msuozzo commented
Alright I've rebased the fix for the legacy test to the new functional one.

Unfortunately, your PR seems to run into the issue that py3.8 AST has different (read: more accurate) column metadata than do previous versions. Maybe add a config param to all tests to not check columns before py3.8?

2021-01-04 19:25 UTC, Pierre-Sassoulas commented
Ok, testing columns is not as easy as I thought, it might take some time to make it work from python interpreters above 3.8. I'll probably wait for #3959 and #3965 to be resolved.

2021-01-04 19:27 UTC, Pierre-Sassoulas approved these changes

2021-01-04 19:27 UTC, Pierre-Sassoulas commented on tests/functional/e/excess_escapes.py
> +# +3:[anomalous-backslash-in-string]
👍

2021-01-04 21:11 UTC, merged

2021-01-04 21:14 UTC, Pierre-Sassoulas commented
Pretty useful MR, I remember having to search for the offending backslash in the whole docstring. This will make a lot of lives easier :) Congratulation on your first contribution to pylint !

2021-01-04 23:56 UTC, msuozzo commented
Thanks so much @Pierre-Sassoulas! And thanks for the review and for implementing column-based testing (even though it can't be merged immediately)!