Fix #2498: add generated-members match against the qualified name
PyCQA/pylint pull request #4038
Opened 2021-01-22 13:31 UTC by graingert

## Steps

    * [x]  Add yourself to CONTRIBUTORS if you are a new contributor.

    * [x]  Add a ChangeLog entry describing what your PR does.

    * [x]  If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.

    * [x]  Write a good description on what the PR does.

## Description
A continuation of https://github.com/PyCQA/pylint/pull/3634
This PR fix #2498: previously, `generated-members` only matched against the node string (e.g. `service.files`) or against the node attribute name (e.g. `files`).

With this change, the qualified name can also be matched (e.g. `googleapiclient.discovery.Resource.files`)
## Type of Changes
	Type
✓ 	bug Bug fix
## Related Issue

Closes #2498

2021-01-22 13:33 UTC, graingert commented on pylint/checkers/typecheck.py
> +
```suggestion
```

2021-01-22 13:34 UTC, graingert commented on pylint/checkers/typecheck.py
> +            if any(
```suggestion
            qualname = "{}.{}".format(owner.pytype(), node.attrname)
            if any(
```

2021-01-22 13:38 UTC, graingert commented on pylint/checkers/typecheck.py
> +        return [re.compile(exp) for exp in generated_members]
```suggestion
        return tuple(re.compile(exp) for exp in generated_members)
```

2021-01-23 10:50 UTC, graingert commented
@PCManticore I'm not sure how to add a test for this

2021-01-23 10:50 UTC, graingert commented
also do we want to deprecate the old behaviour?

2021-01-24 09:27 UTC, Pierre-Sassoulas requested changes
Looks good, thank you ! Could you just add functional tests for this in `tests/functional/` ? Please rebase on master first, the format for functional test changed this morning :)

2021-01-27 14:04 UTC, graingert commented
hmm it's broken regression_property_no_member_2641 and I'm not sure why

2021-01-27 17:56 UTC, Pierre-Sassoulas approved these changes
Thank, you the functional tests are on point. I don't know what broke the other one but I'll merge that once it's fixed.

2021-01-27 17:57 UTC, Pierre-Sassoulas commented on tests/functional/g/generated_members.txt
> +no-member:13:6::Instance of 'Klass' has no 'spam' member:INFERENCE
```suggestion
no-member:13:15::Instance of 'Klass' has no 'spam' member:INFERENCE
```
If you're feeling brave the column can probably be placed at the `s` of spam, but this is a different issue than the one you're trying to fix :)

2021-02-02 17:40 UTC, Pierre-Sassoulas commented
Hmm, it looks like master is somehow broken, because I don't know how #4058 can break tests otherwise. Strange. The issue is most probably not in your code, rebasing should fix the problem once master is fixed. Sorry if you took time to troubleshoot that.

2021-02-06 21:21 UTC, hippo91 commented
@graingert @Pierre-Sassoulas sorry about that. The failing CI is due to my last astroid commit. I am currently working on a fix.

2021-02-07 09:36 UTC, PCManticore approved these changes

2021-02-15 20:37 UTC, Pierre-Sassoulas commented
Will be merged in #4092 and release in 2.7, thank you for your work on this @graingert  :)

2021-02-15 20:37 UTC, closed without merging