Fix False positive on Enum.__members__.items()
PyCQA/pylint pull request #4135
Opened 2021-02-23 06:09 UTC by ikraduya

## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [ ] Write a good description on what the PR does.

## Description
Fix #4123 issue about "False positive on Enum.__members__.items()". I add a conditional at _emit_no_member function in typecheck.py.

I am curious if there are any other cases similar to this one.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
|   | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |

## Related Issue
Closes #4123

2021-02-23 19:14 UTC, Pierre-Sassoulas requested changes
Thank you for this fix, we're going to cherry-pick it to 2.7.2, could you rebase and add a quick summary in `What's New in Pylint 2.7.2?` in `Changelog`, please ?

2021-02-24 03:12 UTC, ikraduya commented
Sure, maybe I could also add `__members__.values` and `__members__.keys` as well?
As stated from this https://github.com/PyCQA/pylint/issues/4123#issuecomment-784518440

2021-02-24 07:43 UTC, Pierre-Sassoulas commented
+1, closing two bugs with one MR is always nice :D

2021-02-24 19:41 UTC, Pierre-Sassoulas approved these changes

2021-02-24 19:44 UTC, Pierre-Sassoulas commented
Thank you for the update @ikraduya , I'll merge as soon as pre-commit is fixed.

2021-02-27 18:11 UTC, cdce8p requested changes
Could you rebase this branch onto the current `master` and force push it?
That would take care of some duplicate commits.

2021-02-27 18:11 UTC, cdce8p commented on ChangeLog
> +
```suggestion

```
There are two trailing-whitespaces here which cause the pre-commit check to fail.
If you want, you could also run pre-commit locally with:
```bash
pip install pre-commit
pre-commit install
```
That will run the pre-commit checks on every commit.

2021-02-27 20:18 UTC, Pierre-Sassoulas commented
@ikraduya we have a sunday 28 at 8pm (tomorrow) for the release of `2.7.2` if we want this to be in the next debian :)

2021-02-27 20:27 UTC, merged

2021-02-27 20:38 UTC, Pierre-Sassoulas commented
I squashed everything and used the fix by @cdce8p, it's all good. Thank you for the fix !