Fix Enum invalid name with snake_case preset
PyCQA/pylint pull request #4162
Opened 2021-03-01 02:36 UTC by cdce8p

## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [ ] Write a good description on what the PR does.

## Description
Fixes an issue where Enum constants would be name checked as `class_attributes` and thus the name preset didn't apply correctly. The Enum check was introduced with #3896

cc: @iFreilicht

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
|   | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |

## Related Issue

Closes: #4149

2021-03-01 12:18 UTC, iFreilicht requested changes
This doesn't fix the bug I described in #4149. I cloned your branch and tried my minimum example, and I still get the exact same output:

```
python3 ../pylint a.py
************* Module a
a.py:4:4: C0103: Class attribute name "USER" doesn't conform to snake_case naming style (invalid-name)
a.py:5:4: C0103: Class attribute name "KERNEL" doesn't conform to snake_case naming style (invalid-name)

------------------------------------------------------------------
Your code has been rated at 5.00/10 (previous run: 5.00/10, +0.00)
```

From the test you added it also looks like you're checking for the Enum class name, but the issue is about the class attributes of an Enum, which are detected as both a class attribute and a constant. This is correct, but `const-naming-style` should be prioritized over `class-attribute-naming-style`.

Maybe you fixed some other bug, but I don't know the codebase enough to judge that.

2021-03-01 18:03 UTC, Pierre-Sassoulas approved these changes
I see you retconned the changelog too, thanks ;)

2021-03-01 18:07 UTC, cdce8p commented
@Pierre-Sassoulas I would like to investigate what @iFreilicht said before you merge it. If that's ok.

2021-03-01 18:52 UTC, cdce8p commented
@iFreilicht I looked at it again. Are you sure you tested the correct patch? The change I did makes sure that only the `const-naming-style` is apply to enum value, since they are more comparable to constants then class attributes.

At the moment (version `2.7.2`) if the `const` check is ok it checks as `class-attribute`. To give you an example
```py
from enum import Enum
class System2(Enum):
    user_KERNEL = 0
```
Running
```bash
pylint --class-attribute-naming-style=snake_case a.py
```
Would print
```
************* Module a
test_enum.py:5:4: C0103: Constant name "user_KERNEL" doesn't conform to UPPER_CASE naming style (invalid-name)
test_enum.py:5:4: C0103: Class attribute name "user_KERNEL" doesn't conform to snake_case naming style (invalid-name)
```

With the patch it only reports the first error:
```
************* Module a
test_enum.py:5:4: C0103: Constant name "user_KERNEL" doesn't conform to UPPER_CASE naming style (invalid-name)
```

2021-03-01 19:41 UTC, iFreilicht commented
I don't know what I'm doing wrong, but I'm certain I'm in the correct folder and on the correct commit:

```
$ git rev-parse HEAD # On the right commit
cdf879b2d9d8198ec11fc482fda9cf6f73a68f04
$ ls -al | grep pylint # I'm in the right directory
-rwxrwxrwx 1 felix felix    196 Mar  1 13:04 .old.pylintrc
drwxrwxrwx 1 felix felix   4096 Mar  1 13:05 pylint
-rwxrwxrwx 1 felix felix  11244 Mar  1 13:01 pylintrc
$ python pylint --version # But pylint version is reported weirdly
pylint 2.6.0
astroid 2.4.2
Python 3.9.1 (default, Feb  6 2021, 06:49:13) 
[GCC 10.2.0]
```

If I run from the git directory, I get no errors at all, no matter how bad the code is.

If I run from a different directory, like so:

    python pylint/pytlint --class-attribute-naming-style=snake_case a.py

I get the same error as before. Even with your updated a.py, I get something different:

```
python pylint/pylint --class-attribute-naming-style=snake_case a.py                                                                                                                                                     
************* Module a
a.py:3:4: C0103: Class attribute name "user_KERNEL" doesn't conform to snake_case naming style (invalid-name)
```

I also tried to install from git directly in a venv:

```
$ pip install git+https://github.com/cdce8p/pylint.git@cdf879b2d9d8198ec11fc482fda9cf6f73a68f04
$ pylint --class-attribute-naming-style=snake_case a.py
************* Module a
a.py:3:4: C0103: Class attribute name "user_KERNEL" doesn't conform to snake_case naming style (invalid-name)
```

I really don't know what else to try, but if you tested this, that's ok. I'm sure it'll work once I install the next version via PyPi.

2021-03-02 01:41 UTC, cdce8p commented
> If I run from the git directory, I get no errors at all, no matter how bad the code is.

The `invalid-name` check is disabled for the pylint directory (inside the `pylintrc` file).

> python pylint --version # But pylint version is reported weirdly

This most likely means that you aren't using the correct version or haven't installed it properly.
You could try running `pip install -e .` inside the `pylint` folder.

> I really don't know what else to try, but if you tested this, that's ok. I'm sure it'll work once I install the next version via PyPi.

You could try installing the commit via pip. Just to eliminate any other factors: create a new folder outside the `pylint` directory, create and activate a new virtual environment. Then run
```bash
pip install -U git+git://github.com/PyCQA/pylint.git@cdf879b2d9d8198ec11fc482fda9cf6f73a68f04
```
Afterwards, check do `pylint --version` and check the enum class if it works.

2021-03-02 08:45 UTC, iFreilicht commented
Alright, got it to work now. I made the mistake of leaving out the `-U` when trying to install from git in the venv. Thank you so much for your patience! ❤️

2021-03-02 08:45 UTC, iFreilicht approved these changes

2021-03-02 08:46 UTC, merged