Fix private method hidden by ancestor class attribute
PyCQA/pylint pull request #4177
Opened 2021-03-03 01:31 UTC by tiagohonorato

## Steps

- [x] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description

A class defined private method won't be hidden by an ancestor class private attribute as the class will mangle the latter to avoid naming collisions. This fixes a false positive for ``method-hidden`` when using private attributes and methods.

Signed-off-by: Tiago Honorato <tiagohonorato1@gmail.com>

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
| ✓  | :sparkles: New feature |
| ✓  | :hammer: Refactoring  |
| ✓  | :scroll: Docs |

## Related Issue

Closes #3936

2021-03-06 13:59 UTC, Pierre-Sassoulas requested changes
Thank you for working on this. Could you add another test with a protected attribute that check that the ``method-hidden`` is raised in this case ?

```python
            class Parent:
                def __init__(self):
                    self._protected = None
            class Child(Parent):
                def _protected(self): # [method-hidden]
                    pass
```

2021-03-08 01:08 UTC, tiagohonorato commented
Hi @Pierre-Sassoulas, thank you for the suggestion. I will add that test!

2021-03-09 08:16 UTC, Pierre-Sassoulas approved these changes

2021-03-21 19:16 UTC, Pierre-Sassoulas commented on ChangeLog
> +
```suggestion
* Fix false positive for ``method-hidden`` when using private attribute and method

  Closes #3936

* Fix issue with Enums and ``class-attribute-naming-style=snake_case``

```

2021-03-21 19:22 UTC, Pierre-Sassoulas commented on ChangeLog
> +
```suggestion

```

2021-03-21 19:29 UTC, merged