Skip docparams checker on nodes within exempted functions.
PyCQA/pylint pull request #4182
Opened 2021-03-04 00:47 UTC by shvenkat

Certain functions have a "docstring exemption". This includes functions whose name matches the `no-docstring-rgx` option, or whose docstring is not longer than the `docstring-min-length` option (if set to a positive value). These functions are partially exempt from the `parameter_documentation` checker. This PR fixes this checker to complete the exemption.

In `pylint/extensions/docparams.py`, functions matching either of the above options are skipped by the `visit_functiondef` method. Here, this logic is also applied in the other `visit_*` methods: `visit_raise`, `visit_return`, `visit_yield` and `visit_yieldfrom`.

## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [ ] Write a good description on what the PR does.

## Description

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

## Related Issue

2021-03-06 13:49 UTC, Pierre-Sassoulas requested changes
Thank you for the merge request, this looks nice. Could you add some typing and maybe create a test ? Maybe checking the ``call_count`` on a mock?

2021-03-06 13:49 UTC, Pierre-Sassoulas commented on pylint/extensions/docparams.py
> +    def visit_functiondef(self, node):
We dropped python 3.5 some time ago ;)

```suggestion
    def visit_functiondef(self, node: astroid.scoped_nodes.Function) -> None:
```

2021-06-30 02:44 UTC, shvenkat commented
Thanks for the typing suggestion. I accepted it as a commit here.

> Maybe checking the call_count on a mock?

I have no idea how to do that :) Any suggestions or pointers?

2021-06-30 05:58 UTC, Pierre-Sassoulas commented
>Any suggestions or pointers?

Sure, you can read more about call_count [here](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.call_count)

2021-11-19 23:36 UTC, n-thumann commented
Any update on this? I'd love so see this merged :v:

2021-11-20 07:50 UTC, Pierre-Sassoulas commented
> Any update on this?

This need a rebase, tests and typing, it seems @shvenkat is not available to do it but I would merge it if someone build on it.

2022-04-01 21:10 UTC, DanielNoord commented
I'm going to close this as it has become stale.

@n-thumann If you can provide a code example in which this would benefit you I would be willing to take a look at this again. For now, I don't immediately see how this would benefit us. I believe the `visit_raise` depend on us actually finding a docstring in the `visit_functiondef` function, so if we skip there because of regex we should also skip in `visit_raise`.

2022-04-01 21:10 UTC, closed without merging