Implemented new checker ``invalid-class-object``
PyCQA/pylint pull request #4510
Opened 2021-05-25 15:50 UTC by yushao2

## Steps

- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description

Implemented a new checker ``invalid-class-object``, which checks for cases where a non-class object is assigned to the ``__class__`` attribute

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Related Issue
Closes #585

2021-05-25 15:51 UTC, yushao2 commented
P.S.: I'm not too familiar with working with ``__class__`` myself, so the functional test suite might be incomplete

2021-05-25 17:55 UTC, Pierre-Sassoulas requested changes
Nice, that's an old issue you're fixing here !

2021-05-25 17:55 UTC, Pierre-Sassoulas commented on pylint/checkers/classes.py
> +    def visit_assignattr(self, node: astroid.AssignAttr) -> None:
Maybe we could add the decorator here ?

2021-05-25 19:02 UTC, Pierre-Sassoulas approved these changes

2021-05-25 21:40 UTC, cdce8p reviewed
Why did you move the tests cases? Not sure this is really necessary. If it is, it would probably be better to do it in a separate PR.

2021-05-26 01:48 UTC, yushao2 commented
> Why did you move the tests cases? Not sure this is really necessary. If it is, it would probably be better to do it in a separate PR.

An error was being thrown that the invalid subfolder had too many test cases.

Maybe i can undo moving all test cases, and keep this in a subfolder. What do you think?

2021-05-26 06:14 UTC, Pierre-Sassoulas commented
I think we can keep the file moved the way you did, it's not confusing. Maybe in another MR that we'll rebase this one on ?

2021-05-26 09:00 UTC, yushao2 commented
> I think we can keep the file moved the way you did, it's not confusing. Maybe in another MR that we'll rebase this one on ?

sorry, so I should leave the files as how i moved them in this MR? just to clarify

2021-05-26 09:12 UTC, Pierre-Sassoulas commented
Yes, looks fine to me, there is a lot of functional tests starting by "invalid" so separating them again like you did make sense.

2021-05-26 09:18 UTC, yushao2 commented
> Yes, looks fine to me, there is a lot of functional tests starting by "invalid" so separating them again like you did make sense.

for now, in this MR, i separated _only those_ with > 2 files so that it would not be too heavy on the refactoring

2021-05-26 10:26 UTC, cdce8p approved these changes
Ok, let's merge it then!

2021-05-26 10:49 UTC, merged