Added support for deprecated method alias
PyCQA/pylint pull request #4619
Opened 2021-06-27 21:22 UTC by matusvalo

## Steps

- [X] Add yourself to CONTRIBUTORS if you are a new contributor.
- [X] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [X] Write a good description on what the PR does.

## Description

This PR adds support for deprecated methods/functions which are just aliases to new names.
Examples of such methods/functions:

* threading.currentThread
* threading.activeCount
* threading.Condition.notifyAll
* threading.Event.isSet
* threading.Thread.setName
* threading.thread.getName
* threading.Thread.isDaemon
* threading.Thread.setDaemon

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|     | :sparkles: New feature |
|     | :hammer: Refactoring   |
|     | :scroll: Docs          |

## Related Issue

Closes #4618

2021-06-28 18:41 UTC, Pierre-Sassoulas requested changes
Thank you for this new feature, I have a small remark, before merging but this look great 👍

2021-06-28 18:41 UTC, Pierre-Sassoulas commented on tests/checkers/unittest_deprecated.py
> +            deprecated_method = _deprecated_method
Could you also add a functional test so it's possible to check that the warning is on the proper line ? Right now we're checking that something is raised for the whole node without checking the line and column.

2021-06-29 16:51 UTC, Pierre-Sassoulas commented on tests/checkers/unittest_deprecated.py
> +            deprecated_method = _deprecated_method
I've done it because I want your feature to be in 2.9.0 :)

2021-06-29 16:51 UTC, Pierre-Sassoulas approved these changes

2021-06-29 17:12 UTC, merged

2021-06-29 19:45 UTC, matusvalo commented
Thank you @Pierre-Sassoulas ! I come here to implement your feedback, but it seems you were faster :-D.