Add ignored-parents option to design checker
PyCQA/pylint pull request #4758
Opened 2021-07-27 16:34 UTC by 9999years

This allows users to specify classes to ignore while counting parent
classes.

Partially closes #3057

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Closes #XXX

2021-07-27 18:34 UTC, Pierre-Sassoulas requested changes
Thank you for the merge request and the added option, this looks nice. I left some comments. Could you also add a new functional test in tests/functional/.../too_many_ancestors.py with a configuration file, please ?

2021-07-27 18:34 UTC, Pierre-Sassoulas commented on ChangeLog
> +* Added ``ignored-parents`` option to the design checker to ignore classes
I think this should be in 2.10 as it's a new feature.

2021-07-27 18:34 UTC, Pierre-Sassoulas commented on pylint/checkers/design_analysis.py
> +    node: nodes.ClassDef, ignored_parents: FrozenSet[str]
Good job adding the typing 👍

2021-07-27 18:34 UTC, Pierre-Sassoulas commented on pylint/checkers/design_analysis.py
> +        print(parents)
Debug print forgotten here :)

2021-07-27 18:34 UTC, Pierre-Sassoulas commented on tests/checkers/unittest_design.py
> +REGR_DATA_DIR = str(Path(__file__).parent / ".." / "regrtest_data")
```suggestion

```

2021-07-27 18:34 UTC, Pierre-Sassoulas commented on tests/checkers/unittest_design.py
> +# Copyright (c) 2021 Rebecca Turner <rturner@starry.com>
This is automated, don't worry about it next time :)

2021-07-27 19:18 UTC, 9999years commented
Added a functional test -- should I keep the `tests/checkers/unittest_design.py` file I added or is just the functional test OK?

2021-07-27 19:23 UTC, Pierre-Sassoulas approved these changes
Thank you for implementing the functional tests ! It's true that the unittest could be a duplicate now. I don't know for sure if it's covering more line than simply the functional test.

2021-07-27 19:24 UTC, 9999years commented
I'll leave it -- it won't hurt and it'll make it easier for the next person who wants to unit test the design checker.

2021-07-27 19:35 UTC, Pierre-Sassoulas commented
There will be a slight delay before merging as we want to release 2.9.6 first and this is going in 2.10 🙂

2021-07-28 19:45 UTC, merged

2021-07-28 19:45 UTC, Pierre-Sassoulas commented
Thank you again for your work on this, this will be available in 2.10.0 !