Refactor ``--list-msgs`` & ``--list-msgs-enabled``
PyCQA/pylint pull request #4793
Opened 2021-08-03 15:31 UTC by DanielNoord

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |

## Description

Both options now show which messages can't be emitted with the current interpreter. This makes function more like their name implies. Code clearly shows in which order/format the messages are emitted.
This closes #4778

2021-08-03 18:31 UTC, Pierre-Sassoulas requested changes
Nice job ! Could we refactor a little further and create a common function to recover emitable/non-emittable ? This way ``list_messages_enabled`` would loop on the result of this function and the other one would use them directly.

2021-08-03 18:31 UTC, Pierre-Sassoulas commented on pylint/lint/pylinter.py
> +        for message in self.msgs_store.messages:
Nice refactor 👍

2021-08-03 19:10 UTC, DanielNoord commented
Where should I put this common function? Is there a good place for utils function for files in different directories?

Thinking of:
```python
def find_emittable_messages(
    messages: List[MessageDefinition],
) -> Tuple[List[MessageDefinition], List[ValuesView[MessageDefinition]]]:
    emittable = []
    non_emittable = []
    for message in messages:
        if message.may_be_emitted():
            emittable.append(message)
        else:
            non_emittable.append(message)
    return emittable, non_emittable
```

2021-08-03 19:15 UTC, Pierre-Sassoulas commented
``MessageDefinitionStore`` is the logical place so you don't have to provide the messages (they're already a class attribute).

2021-08-03 19:54 UTC, Pierre-Sassoulas approved these changes
Thank you !

2021-08-03 20:05 UTC, merged

2021-08-05 13:55 UTC, scop commented
FYI, my recent pylint bash completion PR at https://github.com/scop/bash-completion/pull/562 is what triggered to me to file #4778. Looking at the code here it seems my scraper would be still doing the right thing after these changes, cool.

The scraper is _far_ from pretty, but all things considered I don't think we have a better choice at the moment, and if we want to support old pylint versions out there, new additions of e.g. better machine parseable outputs for these in new releases wouldn't help either.