``pyreverse``: refactor tests
PyCQA/pylint pull request #4815
Opened 2021-08-08 13:59 UTC by DudeNr33

This should be the last "preparation" MR before the new ``pyreverse`` features (PlantUML output and colored output) can be merged.

In this MR one of the initial review remarks of the original MR is addressed: the existing tests for ``pyreverse`` imported from one another, and some proper fixtures can help clean up the code.
Additionally, I moved the tests to a separate subdirectory so the hierarchy under ``tests`` matches the one under ``pylint``, and renamed the test modules to better conform to the naming conventions of the remaining test modules.

I also included some tests that I forgot to merge when I refactored the ``Printer`` class.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

2021-08-08 14:00 UTC, DudeNr33 commented on .pre-commit-config.yaml
> +        exclude: tests/functional/|tests/input|tests(/.*)*/data|tests/regrtest_data/|tests/data/|tests(/.*)+/conftest.py|doc/|bin/
``mypy`` is not happy with having two modules with the same name inside a directory tree without ``__init__.py`` files.
Also, all ``data`` folders should probably be ignored, the original exclude pattern listed ``tests/extensions/data`` and ``tests/data`` separately.

2021-08-08 14:01 UTC, DudeNr33 commented on pylint/testutils/pyreverse.py
> +    return project_from_files([module], _astroid_wrapper, project_name=name)
This method was used in several test modules, but is not suitable to be replaced by a fixture. That's why I put it under ``pylint.testutils``.

2021-08-08 14:02 UTC, DudeNr33 commented on tests/pyreverse/test_utils.py
> +
Those tests were initially inside ``test_writer.py``, but I think they belong in an own module.

2021-08-08 20:01 UTC, Pierre-Sassoulas requested changes
Thank you for making digestible little part for me 😄  I made minor remarks but this looks mergeable already.

2021-08-09 04:45 UTC, DudeNr33 commented on pylint/testutils/pyreverse.py
> +# For details: https://github.com/PyCQA/pylint/blob/master/LICENSE
Ah, missed that one too. Changed it.

2021-08-09 04:46 UTC, DudeNr33 commented
Thanks for the review. Good idea to return a callable from a fixture, haven't thought of that before. :)

2021-08-09 18:00 UTC, Pierre-Sassoulas approved these changes
👍

2021-08-09 18:00 UTC, merged