Add consider-if-expression extension
PyCQA/pylint pull request #4871
Opened 2021-08-19 02:15 UTC by nickdrozd

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description

Closes #4366

2021-08-19 02:36 UTC, nickdrozd commented
Something is off with the functional test specification. Am I missing something obvious?

2021-08-19 06:42 UTC, Pierre-Sassoulas requested changes
Hey, thank you for implementing this. Could you revert all the ternary changes that do not fit on one line using black ? I think bigger ternary make the code harder to understand.

2021-08-19 10:37 UTC, cdce8p commented
> Hey, thank you for implementing this. Could you revert all the ternary changes that do not fit on one line using black ? I think bigger ternary make the code harder to understand.

I agree with that. Ternary ifs should only really be used for short conditions, something like
```py
var = 2 if some_var else 3
```

2021-08-19 10:55 UTC, Pierre-Sassoulas commented
To the point that I'm wondering if the checker should not be changed to :
- if it's a ternary and it's longer than 88 characters, tell the user to remove the ternary
- It's it's not a ternary and it's shorter than 88 characters, tell the user to consider a ternary

What do you think @nickdrozd  ?

2021-08-19 11:01 UTC, cdce8p commented
> To the point that I'm wondering if the checker should not be changed to :
> 
> * if it's a ternary and it's longer than 88 characters, tell the user to remove the ternary
> * It's it's not a ternary and it's shorter than 88 characters, tell the user to consider a ternary

I'm really not sure we should enforce any of it. IMO it doesn't make the code inherently better to use either.
I.e. even for the existing pylint code I don't think we should do most of these changes.

2021-08-19 14:48 UTC, nickdrozd commented
Okay, I took out the changes that don't result in one-liners.

Personally, I would change all of them. It's not about lines of text, it's about complexity -- one single assign statement is less complex than two. It's a shame that Python makes if-expressions so clunky to use. In Lisp and Rust if-expressions are used all over the place with no problems.

As for the check itself, I think it's okay if it suggests some more extreme changes, like if-expressions that would get broken across multiple lines. The check is an extension, disabled by default. So anyone who enables the extension can be safely assumed to be a relatively sophisticated Pylint user, and therefore also someone who can deal with any false positives or iffy cases.

2021-08-19 21:10 UTC, Pierre-Sassoulas requested changes
Thank you for cleaning up the MR, I left some comment, mostly I think the expected name is "ternary operator" or "ternary conditional".

2021-08-19 21:10 UTC, Pierre-Sassoulas commented on pylint/extensions/consider_if_expression.py
> +    name = "consider_if_expression"
```suggestion
    name = "consider_ternary_expression"
```

2021-08-19 21:10 UTC, Pierre-Sassoulas commented on pylint/extensions/consider_if_expression.py
> +            "Consider rewriting as an if-expression",
```suggestion
            "Consider rewriting as a ternary if-expression",
```

2021-08-19 21:10 UTC, Pierre-Sassoulas commented on pylint/extensions/consider_if_expression.py
> +            "consider-if-expression",
```suggestion
            "consider-ternary-expression",
```

2021-08-19 21:10 UTC, Pierre-Sassoulas commented on pylint/extensions/consider_if_expression.py
> +            "rewritten with a single assingment and an if-expression",
```suggestion
            "rewritten with a single assignment as a ternary conditional",
```

2021-08-19 21:10 UTC, Pierre-Sassoulas commented on pylint/extensions/consider_if_expression.py
> +    def visit_if(self, node):
Could you add the typing, please ? :)

2021-08-19 21:12 UTC, Pierre-Sassoulas commented
> As for the check itself, I think it's okay if it suggests some more extreme changes,

Yes I agree, I was trying to transform it into something complicated that I would personally use, but if someone want only ternary and have to activate this plugin, then it can be very opinionated without problems.

2021-08-20 17:27 UTC, Pierre-Sassoulas approved these changes
Great work, thank you !

2021-08-20 17:27 UTC, merged

2021-09-03 06:40 UTC, zrothberg commented
https://nickdrozd.github.io/2021/09/02/new-pylint-checks.html

This dude just used your repo to write a terrible article.