Emit a correct invalid-name message when using multi-naming style.
PyCQA/pylint pull request #4924
Opened 2021-08-27 22:48 UTC by yilei

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |

## Description

This PR fixes the `invalid-name` error messages when using multi-naming style.

Previously, given `--function-rgx=(?:(?P<UP>[A-Z]+)|(?P<down>[a-z]+))$` and the code:

```
def FOO():
    pass
def UPPER():
    pass
def lower():
    pass
```

It would emit a message: ``Function name `lower` doesn't conform to '(?:(?P<UP>[A-Z]+)|(?P<down>[a-z]+))$' pattern [invalid-name]``.

The message is misleading as `lower` *does* conform to `(?:(?P<UP>[A-Z]+)|(?P<down>[a-z]+))$`. It's just not the prevalent group "UP".

After this commit, the message becomes: ``Function name `lower` doesn't conform to UP group in the '(?:(?P<UP>[A-Z]+)|(?P<down>[a-z]+))$' pattern [invalid-name]``

2021-08-28 06:48 UTC, Pierre-Sassoulas requested changes
Thank you for this change this would make the message clearer indeed. Could you add typing on modified functions, please ? We're trying to add it progressively. Also, it seems that there was nothing to test this before but could you add functional tests for it ? In ``tests/functional/i/invalid_name_rmultinaming_style.py`` by adding a .rc file with multi naming regex in it for example :)

2021-08-30 18:29 UTC, yilei commented
I added type annotations and a function test, please take another look, thanks @Pierre-Sassoulas

2021-08-30 18:35 UTC, Pierre-Sassoulas requested changes
Thank you for the new tests, I think it's perfect. I forgot about the need to add a little message in whatsnew, this will be released in 2.11 :)

2021-08-30 18:35 UTC, Pierre-Sassoulas commented on ChangeLog
```suggestion
* The ``invalid-name`` message is now more detailed when using multiple naming style regexes.

```
Could you also add that in docs/whatsnew/2.11, please ?

2021-08-30 18:46 UTC, yilei commented
Done.

2021-08-30 19:28 UTC, Pierre-Sassoulas commented on pylint/checkers/base.py
> +            hint = "the `%s` group in the " % prevalent_group + hint
```suggestion
            hint = f"the `{prevalent_group}{hint}` group in the "
```

2021-08-30 19:49 UTC, yilei commented
The f-string change is incorrect, I pushed a new commit to fix.

2021-08-30 20:11 UTC, merged