No docstring rgx
PyCQA/pylint pull request #5084
Opened 2021-09-28 08:03 UTC by DanielNoord

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :hammer: Refactoring   |

## Description

Turns out we did not handle empty regex options correctly. The referenced issue was broken because whenever the `no_docstring_rgx` option was empty it would try to match `re.compile("")` which always matched and would thus never check a parameter.

The change to `get_global_option()` is necessary for it to actually return a `Pattern[str]` for those options. A problem I couldn't solve was that it is impossible (I think) to tell `mypy` that the option belongs to `GLOBAL_OPTION_PATTERN` and should therefore return a `Pattern[str]`. This is because you can't use `isinstance` on `Literal` and there is no good solution to do this any other way (using `cast` also doesn't work).

/CC @cdce8p Because you helped with #4978 and might have a solution for the `mypy` issue that I don't know about 😄 

Closes #4136

2021-09-28 09:19 UTC, DanielNoord commented
```bash
❯ pip install -e .
Obtaining file:///Users/daniel/DocumentenLaptop/Programming/Github/pylint
Requirement already satisfied: platformdirs>=2.2.0 in /Users/daniel/.pyenv/versions/3.9.6/envs/pylint-3.9.6/lib/python3.9/site-packages (from pylint==2.11.2.dev0) (2.2.0)
Requirement already satisfied: astroid<2.9,>=2.8.0 in /Users/daniel/DocumentenLaptop/Programming/Github/astroid (from pylint==2.11.2.dev0) (2.8.0)
Requirement already satisfied: isort<6,>=4.2.5 in /Users/daniel/.pyenv/versions/3.9.6/envs/pylint-3.9.6/lib/python3.9/site-packages (from pylint==2.11.2.dev0) (5.9.3)
Requirement already satisfied: mccabe<0.7,>=0.6 in /Users/daniel/.pyenv/versions/3.9.6/envs/pylint-3.9.6/lib/python3.9/site-packages (from pylint==2.11.2.dev0) (0.6.1)
Requirement already satisfied: toml>=0.9.2 in /Users/daniel/.pyenv/versions/3.9.6/envs/pylint-3.9.6/lib/python3.9/site-packages (from pylint==2.11.2.dev0) (0.10.2)
Requirement already satisfied: typing-extensions>=3.10.0 in /Users/daniel/.pyenv/versions/3.9.6/envs/pylint-3.9.6/lib/python3.9/site-packages (from pylint==2.11.2.dev0) (3.10.0.0)
Requirement already satisfied: lazy_object_proxy>=1.4.0 in /Users/daniel/.pyenv/versions/3.9.6/envs/pylint-3.9.6/lib/python3.9/site-packages (from astroid<2.9,>=2.8.0->pylint==2.11.2.dev0) (1.6.0)
Requirement already satisfied: wrapt<1.13,>=1.11 in /Users/daniel/.pyenv/versions/3.9.6/envs/pylint-3.9.6/lib/python3.9/site-packages (from astroid<2.9,>=2.8.0->pylint==2.11.2.dev0) (1.12.1)
Requirement already satisfied: setuptools>=20.0 in /Users/daniel/.pyenv/versions/3.9.6/envs/pylint-3.9.6/lib/python3.9/site-packages (from astroid<2.9,>=2.8.0->pylint==2.11.2.dev0) (56.0.0)
Installing collected packages: pylint
  Attempting uninstall: pylint
    Found existing installation: pylint 2.11.2.dev0
    Uninstalling pylint-2.11.2.dev0:
      Successfully uninstalled pylint-2.11.2.dev0
  Running setup.py develop for pylint
Successfully installed pylint-2.11.2.dev0
WARNING: You are using pip version 21.2.2; however, version 21.2.4 is available.
You should consider upgrading via the '/Users/daniel/.pyenv/versions/3.9.6/envs/pylint-3.9.6/bin/python3.9 -m pip install --upgrade pip' command.
❯ pylint '/Users/daniel/DocumentenLaptop/Programming/Github/pylint/pylint/utils/utils.py'

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

Not sure what `pre-commit` is failing on. Passes locally when installing `pylint` from working directory.

2021-09-28 11:58 UTC, cdce8p requested changes

2021-09-28 11:58 UTC, cdce8p commented on pylint/utils/utils.py
> +        raise ValueError(f"Incorrect option type for option: {option}")
`get_global_option` shouldn't modify the return value. You probably want to move that logic to a custom validator here:
https://github.com/PyCQA/pylint/blob/20304a6cfb0dedec8ca7878822b8db1fd3cc71cc/pylint/config/option.py#L81
That should also fix the mypy issue.

2021-09-29 18:49 UTC, DanielNoord commented
I wonder why the default value for ``no_docstring_rgx`` was `^_`. I changed this because I can

2021-09-29 18:49 UTC, closed without merging