Fix a crash if ``str.format`` is referenced without being called
PyCQA/pylint pull request #5109
Opened 2021-10-03 17:24 UTC by timmartin

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

If the `str.format` function was being referenced (not called) in the keyword argument to a function, the `consider-using-f-string` checker was crashing due to attempting to obtain the `.args` from something that wasn't a call object. Referencing format without calling it in this way might be a mistake, but that should probably be another checker.

Closes #5058

2021-10-03 18:22 UTC, DanielNoord requested changes
Thanks for this fix and your investigation in #5058. I initially made this checker and am really happy you found this!

I requested two small changes which I think would improve this commit/merge, but the general idea of the commit is good!

2021-10-03 18:22 UTC, DanielNoord commented on pylint/checkers/refactoring/recommendation_checker.py
> +            if not isinstance(node.parent.parent, nodes.Call):
I'm wondering if we can't merge this with the check on L345. If the check on L349 passes, L345 should pass as well. We would only need to add both use cases to the comment on L344.

2021-10-03 18:22 UTC, DanielNoord commented on tests/functional/c/consider/consider_using_f_string.py
> +    def wrap_print(value):
I think we can move this to the bottom of this file. Perhaps with a comment saying:
`Non valid code that shouldn't crash the checker`.
That would decrease the size of this diff as all line numbers don't change.

2021-10-03 19:07 UTC, Pierre-Sassoulas approved these changes
Great analysis and fix @timmartin , thank you. I approve with @DanielNoord's suggestion especially the one that will reduce the diff.

2021-10-06 18:19 UTC, DanielNoord commented
You'll need to merge main to fix the merge conflict, otherwise this looks good to go!

2021-10-06 19:56 UTC, Pierre-Sassoulas commented on ChangeLog
> +* Fixed crash in ``consider-using-f-string`` if ``format`` is not called
Imo order do not matter at all. I even hesitated at some point to explicitly tell contributors to input them at random location so as to reduce merge conflict when another changelog entry is merged in main.

2021-10-06 19:56 UTC, merged