Clarify syntax in pylint.lint example
PyCQA/pylint pull request #5260
Opened 2021-11-05 10:20 UTC by felixvd

This makes the call in the documentation non-trivial, so that [idiots like me](https://stackoverflow.com/questions/69851634/how-to-run-pylint-from-inside-python/69851635#69851635) don't get stuck.

If someone could show how to get the output of the command (as asked [here](https://stackoverflow.com/questions/56081299/how-to-get-report-score-from-pylint-when-run-python-code)), that would also be very helpful to add.

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [ ] Write a good description on what the PR does.

2021-11-05 14:40 UTC, Pierre-Sassoulas requested changes
Thank you for the better example ! I think your commit message `so idiots don't me get stuck.` could be reordered to `so it's harder to get stuck.` More seriously could you add yourself to the contributors, please ? :)

I'll keep the stackoverflow question in mind, I did not manage to make it work myself yet, which is a clue that new documentation will be required.

2021-11-07 09:47 UTC, felixvd commented
Done. I assumed it's not worth making an entry in the file for such a small contribution, but if it's policy then sure.

2021-11-12 16:19 UTC, DanielNoord commented
> I'll keep the stackoverflow question in mind, I did not manage to make it work myself yet, which is a clue that new documentation will be required.

I have investigated this a bit more. Without changes to `Run` I think this is simply impossible. The way we change `.out` and `._output` doesn't really allow to do this with `Run`.
When using `PyLinter` this might be possible, but I'm not sure we want to create documentation telling people to access it directly. In any case, we could open an issue to track this and close this PR (waiting for a change to `Run` seems incorrect).

2021-11-12 16:34 UTC, Pierre-Sassoulas commented
> Without changes to Run I think this is simply impossible.

That was my conclusion too. I had the impression it was a problem with kwargs not being taken into account, but I did not go in depth. Do you want to create the issue @DanielNoord ? 

>  I'm not sure we want to create documentation telling people to access it directly

I pretty much agree, I think we need ``Run`` to be the entry-point. Especially as we will want to make change to Pylinter later as it's so bloated.

2021-11-12 20:07 UTC, DanielNoord commented
Opened an issue to track the `output` issue :)

2021-11-13 12:07 UTC, Pierre-Sassoulas commented on CONTRIBUTORS.txt
> +Contributors
```suggestion
Contributors
```

2021-11-13 12:10 UTC, Pierre-Sassoulas approved these changes
I'm merging as this is still clearer than what we had before. Follow up to be able to recover the output in a stream is #5295.

2021-11-13 12:10 UTC, merged