Fixed extremely long processing of long lines with comma's
PyCQA/pylint pull request #5534
Opened 2021-12-16 11:05 UTC by DanielNoord

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #5483 

The problem was not actually in a regex pattern but in how we checked lines for trailing comma's.

The test is a bit arbitrary and the timing was difficult to get right: I don't want to have the tests fail because the CI runner has an off-day. But I checked with the original reported code and this is much faster.

2021-12-16 11:18 UTC, DanielNoord commented
I guess I'll up the amount of time the test can be allowed:
https://github.com/PyCQA/pylint/runs/4546524788?check_suite_focus=true

`pypy` needs some more time to process this apparently. Note that the test pass on Windows and Linux with 30s. I'll try 45.

2021-12-16 11:18 UTC, DanielNoord commented on tests/checkers/unittest_refactoring.py
> +    with timeout(30.0):
```suggestion
    with timeout(45.0):
```

2021-12-16 20:45 UTC, Pierre-Sassoulas reviewed
> pypy needs some more time to process this apparently. Note that the test pass on Windows and Linux with 30s. I'll try 45.

How long was it taking before ? I think it's still a long time especially as the full test suite is 80s long ? I did not check the underlying math problem. We might merge as "better than before" if making this even faster is not easy. (Provided we make sure it's not run by default in standard tests)

2021-12-16 20:49 UTC, DanielNoord commented
On the original issue line a run went from 5s>1s to me, most of which is probably initialisation of pylint itself. 

This test takes about 10s on my laptop, which isn't bad for iterating over 10,000 tuples and their tokens.. 
It was actually a massive improvement, but because of the different test runners and setups it difficult to define a "this is taking too long" time..

Making the test go over 100,000 tuples would make that easier but then the test would take a minute by default which is a bit much for just testing a simple method and an improvement.

2021-12-16 20:52 UTC, DanielNoord commented
I actually thought about just doing 1000 tuples and setting the cut-off at 10s. That would make the test suite faster, but probably risk never actually failing..
I saw test runners performance on GitHub also changes due to how much US users are online... Making it even more difficult to find a good limit.

2021-12-16 21:12 UTC, Pierre-Sassoulas commented
> I saw test runners performance on GitHub also changes due to how much US users are online... Making it even more difficult to find a good limit.

I was searching for a good way to measure performance at some point (as time is not really reliable) and found this : https://pythonspeed.com/articles/consistent-benchmarking-in-ci/. I did not have time to investigate any of it. (The author of this blog post opened an issue in pylint for an unrelated issue in the past)

2021-12-16 21:30 UTC, DanielNoord commented
I did a quick read and this is very interesting, but I don't think applicable to this case.
I might have missed something, but this tool seems mostly useful for seeing if a new change introduce performance improvement or degradation against the previous commit.
In our case we want to set a "default time" this test should take. Setting something like CPU cycles doesn't work as internals of pylint might change and then the value is no longer relevant.
I don't think this change warrants a full "benchmark testing" setup like this post suggest; we should probably use another combination of tests to do the performance benchmark. Something like a combination of all checkers + a few extensions.

2021-12-16 21:39 UTC, Pierre-Sassoulas commented
If we count CPU cycle instead of time we might be able to run the test on 1000 tuples instead of 10 000 as CPU cycles are supposed to be more stable ?

2021-12-16 21:44 UTC, DanielNoord commented
There are so many things that would impact that: config parsing, initialisation of checker classes, invoking pylint, etc. Those could all lead to this test failing without doing anything wrong..

2021-12-16 22:06 UTC, Pierre-Sassoulas commented
Isn't that also true for time ?

2021-12-16 22:09 UTC, DanielNoord commented
Hm yeah, didn't think of it like that 😅 

Anyway, I don't think we can really test this without going out of our way to set up some real advances performance testing, which I don't think this changes warrants.

2021-12-16 22:16 UTC, Pierre-Sassoulas requested changes
The perf increase is amazing ! Concerning test time maybe we could use 1000 tuples and use pypi test's time for the timeout ?

2021-12-16 22:24 UTC, DanielNoord commented
I think 1000 with 8.0 for timeout should work. If you'd like you could suggest this and apply the suggestion. I'm on mobile right now so that's a bit more difficult.

2021-12-16 22:38 UTC, Pierre-Sassoulas commented on tests/checkers/unittest_refactoring.py
> +    with timeout(45.0):
```suggestion
    with timeout(8.0):
```

2021-12-16 22:39 UTC, Pierre-Sassoulas commented on tests/regrtest_data/very_long_line.py
> +very_long_list_ten = [[None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, No
```suggestion
very_long_list = [[None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [N [...]

2021-12-17 16:08 UTC, Pierre-Sassoulas approved these changes

2021-12-17 22:59 UTC, merged