Fix dict comprehension false positive
PyCQA/pylint pull request #5590
Opened 2021-12-23 11:23 UTC by tushar-deepsource

## Type of Changes

Adds a condition where R1717 should not be raised

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #5588

2021-12-23 11:24 UTC, tushar-deepsource commented
How am I still a first time contributor (:

2021-12-23 11:38 UTC, tushar-deepsource commented
> * Tushar Sadhwani (tusharsadhwani): contributor

My personal account is in contributors. Should I add another entry?

2021-12-23 14:42 UTC, Pierre-Sassoulas commented
> My personal account is in contributors. Should I add another entry?

No, but you can add an entry in https://github.com/PyCQA/pylint/blob/main/.copyrite_aliases

2021-12-23 14:45 UTC, Pierre-Sassoulas requested changes
I'd add another test case for the case where the key change and not the value.

2021-12-23 14:45 UTC, Pierre-Sassoulas commented on tests/functional/c/consider/consider_using_dict_comprehension.py
> +dict([(k, v) if v > 0 else (k, 0) for k, v in stuff.items()])  # [consider-using-dict-comprehension]
```suggestion
dict([(k, v) if v > 0 else (k, 0) for k, v in stuff.items()])  # [consider-using-dict-comprehension]
dict([(k, v) if v > 0 else (k*2, v) for k, v in stuff.items()])  # [consider-using-dict-comprehension]
```

2021-12-23 14:45 UTC, Pierre-Sassoulas commented on pylint/checkers/refactoring/refactoring_checker.py
> +                # are different, then don't raise the issue.
```suggestion
                # are different, then don't raise the issue. See #5588
```

2021-12-23 15:15 UTC, tushar-deepsource commented
@Pierre-Sassoulas need a workflow approval

2021-12-23 20:57 UTC, DanielNoord approved these changes

2021-12-23 21:59 UTC, Pierre-Sassoulas approved these changes
Very nice ! Congratulation on becoming a contributor on your second account 😄 Would you mind adding an entry in the copyrite alias to be accounted as a single person (in this MR would work or another one, let me know) ?

2021-12-27 11:16 UTC, tushar-deepsource commented
Done

2021-12-28 15:48 UTC, Pierre-Sassoulas commented
Closing to relaunch github actions.

2021-12-30 18:21 UTC, merged