Config loading
PyCQA/pylint pull request #5594
Opened 2021-12-23 15:22 UTC by DanielNoord

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Follow up to #5591. Diff should be much smaller after that has been merged (adding blocked in the meantime).

This makes it so that whenever a functional test does not have a `.rc` file we still pass a `pylintrc` file to the configuration initialiser.
This does not fix any current problems but allows me (and others) to assume that `_config_initialization` is always ran, also for functional tests that skip instantiating a `Run` object. That allows me to then work within `_config_initialization` for the implementation of `argparse` and make `argparse` and `optparse` work along side each other while we're still working on it.

2021-12-23 22:49 UTC, DanielNoord commented
As to why this is needed: in the current form we don't enter `_config_initialization` when there is not `.rc` file. That doesn't work as I intend to use it to construct the `linter.namespace` attribute.
However, if we run `_config_initialization` without specifying an `.rc` file we will take the default values. The functional tests have not been written with those in mind, so that creates (a lot of) fails. I think this is the better solution.

2021-12-24 08:11 UTC, Pierre-Sassoulas requested changes
I think a little refactor in the handling would make the code clearer.

2021-12-24 08:11 UTC, Pierre-Sassoulas commented on pylint/testutils/lint_module_test.py
> +
```python
if "there is an rc file":
    rc_file = ...
    self._linter.disable("suppressed-message")
    self._linter.disable("locally-disabled")
    self._linter.disable("useless-suppression")
else:
   rc_file = default
...
_config_initialization( # with less try except
```

2021-12-27 10:24 UTC, Pierre-Sassoulas approved these changes
I made suggestion with a commit directly because it was too hard to do in github interface, I'll let you check that before merging :)

2021-12-27 10:55 UTC, DanielNoord commented
Primer is failing after you're latest commit. Could you look into that?
Furthermore, I don't think that the variable should be source, but rather "arguments", but you should recheck that as I'm not 100% sure.

2021-12-27 11:09 UTC, Pierre-Sassoulas commented
> Primer is failing after you're latest commit. Could you look into that?

It seems there are a lot of connectivity issue on a lot of pipelines (timeout when recovering the primer repository but not only). I'll change the variable name :)

2021-12-28 13:43 UTC, Pierre-Sassoulas approved these changes

2021-12-28 15:28 UTC, merged