Handle when the 'ancestors' attribute is not present in an object
PyCQA/pylint pull request #5647
Opened 2022-01-07 21:52 UTC by doctoryes

Fix for issue described here: #5646 

Handle when the 'ancestors' attribute is not present in an object.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #5646

2022-01-07 22:34 UTC, Pierre-Sassoulas requested changes
Thank you for handling this !

Would it be possible to add a regression test in ``tests/functional/`` please ? I'm not sure about what code exactly in [opendx](https://github.com/openedx/XBlock/blob/59c2f28e32548b8cb78b8f7c733bf64689a9a751/xblock/test/test_core.py) is causing the issue but if it's possible to isolate the problem if would be better as the whole file is pretty big.

2022-01-07 22:34 UTC, Pierre-Sassoulas commented on ChangeLog
> +
We don't have a bug fix branch for 2.12 currently so we do not back-port those fix. This is something that we'd need to put into place after we release 2.13 but right now this is going to be in 2.13.

```suggestion

* Fixed handling of missing 'ancestors' object attribute.

  Closes #5646
```

2022-01-07 22:34 UTC, Pierre-Sassoulas commented on pylint/checkers/refactoring/implicit_booleaness_checker.py
> +        except (TypeError, AttributeError):
Nice straightforward fix, I like it :)

2022-01-08 00:01 UTC, DanielNoord commented
Thanks for the fix @doctoryes.

I found a reproducible example:
```python
class MyClassWithProxy:
    @property
    def _my_property(cls):
        return {}


def func():
    xblock = MyClassWithProxy()
    assert MyClassWithProxy._my_property == {}
```

Turns out we're not handling `properties` correctly. In the original code the attribute that is failing is defined as a "lazy" property in one of the sub-sub-subclasses. This smaller example also fails. I'm working on a fix that handles these cases a little more gracefully and will open a PR soon!

2022-01-08 00:14 UTC, DanielNoord commented
Hmm, fixing isn't as easy as I thought. I'll probably work on this somewhere next week.

```python
class ParentWithProperty:
    def _parent_function(cls):
        return {}


class MyClassWithProxy(ParentWithProperty):
    @property
    def _my_property(cls):
        return {}


def func():
    xblock = MyClassWithProxy()
    assert xblock._parent_function == {}
    assert xblock._services_requested == {}
```

Both of these comparisons crash right now. I'll try and fix them both at the same time.

2022-01-08 18:56 UTC, DanielNoord commented
Superseded by #5652.

Thanks @doctoryes for the report and initial work. This should be fixed in `2.13.0`!

2022-01-08 18:56 UTC, closed without merging