Fix ``super-init-not-called`` if parent or ``self`` is a ``Protocol``
PyCQA/pylint pull request #5697
Opened 2022-01-18 15:28 UTC by DanielNoord

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #4790.

Added typing and `confidence` as well.

2022-01-18 16:03 UTC, Pierre-Sassoulas requested changes
Nice, thank you @DanielNoord !

2022-01-18 16:03 UTC, Pierre-Sassoulas commented on tests/functional/s/super/super_init_not_called.txt
> +super-init-not-called:50:4:51:11:TestChild.__init__:__init__ method from base class 'TestParent' is not called:INFERENCE
```suggestion
super-init-not-called:51:4:52:11:TestChild.__init__:__init__ method from base class 'TestParent' is not called:INFERENCE
```

2022-01-18 16:05 UTC, DanielNoord commented on pylint/checkers/classes/class_checker.py
> +        klass = node.parent.frame(future=True)  # type: nodes.ClassDef # See is_method()
The check on L1084 makes sure that this is true. However, `mypy` doesn't pick up on that.

2022-01-18 16:11 UTC, Pierre-Sassoulas commented on pylint/checkers/classes/class_checker.py
> +        klass = node.parent.frame(future=True)  # type: nodes.ClassDef # See is_method()
Ha alright, ``is_method`` was out of side in the review.
```suggestion
        # 'is_method()' is called and makes sure that this is a 'nodes.ClassDef'
        klass = node.parent.frame(future=True)
```
Maybe clearer ?

2022-01-18 16:19 UTC, Pierre-Sassoulas approved these changes
Great fix again 👌

2022-01-18 16:41 UTC, Pierre-Sassoulas commented
Look like there is an issue in the functional test when inference is not Undefined ?

2022-01-18 17:52 UTC, DanielNoord commented
Oh no, stupid mistake. Since I updated the `confidence` for this message all tests that check for this message should be updated. This is a test in another file that I don't change but for which the output should be updated. Fix coming in 30 seconds.

2022-01-18 18:08 UTC, DanielNoord commented
Hmm some version and OS dependent stuff it seems like. Going to take another look tonight!

2022-01-18 18:38 UTC, Pierre-Sassoulas approved these changes

2022-01-18 20:29 UTC, DanielNoord commented
@Pierre-Sassoulas Do we know a contributor who works on Windows? I have no idea why this doesn't work on `3.10` on Windows. Is `Protocol` missing in `typing_extensions` on that version perhaps?

2022-01-18 22:05 UTC, Pierre-Sassoulas commented
> Do we know a contributor who works on Windows?

It's like searching for teeth in a hen's mouth 😄 I'm going to see if I can set up a VM some day. I will need a license before being able to do that anyway.

>  Is Protocol missing in typing_extensions on that version perhaps

The ``6: import-error`` makes me think that you're right.

2022-01-18 22:07 UTC, DanielNoord commented
> > Do we know a contributor who works on Windows?
> 
> It's like searching for teeth in a hen's mouth 😄 I'm going to see if I can set up a VM some day. I will need a license before being able to do that anyway.

I was thinking the same about Linux. I really need it for that `distutils` fix...

> > Is Protocol missing in typing_extensions on that version perhaps
> 
> The `6: import-error` makes me think that you're right.

But I don't understand why. I didn't see any issues about it in the `typing` repo... 😅

2022-01-24 18:09 UTC, DanielNoord commented
Tests are fixed no!

2022-01-24 19:18 UTC, Pierre-Sassoulas approved these changes
👍

2022-01-24 19:19 UTC, merged