Add missing __magic__ methods to `_SPECIAL_METHODS_PARAMS`
PyCQA/pylint pull request #5941
Opened 2022-03-20 18:03 UTC by jpy-git

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Noticed this whilst working on #5938.

These magic methods were missing from the `_SPECIAL_METHODS_PARAMS` variable used for several checks so I've added them in:
- [`__subclasses__`](https://docs.python.org/3/library/stdtypes.html?highlight=__subclasses#class.__subclasses__)
- [`__init_subclass__`](https://docs.python.org/3/library/stdtypes.html?highlight=__subclasses#class.__subclasses__)

This variable gets used in these checkers:
- variables.py
- class_checker.py
- special_methods_checker.py

2022-03-20 19:46 UTC, Pierre-Sassoulas requested changes
Thank you for opening this merge request. I think we need some functional test cases for the checker that would be affected.

2022-03-20 23:11 UTC, jpy-git commented
I've added the functional test for `special_methods_checker.py` to `tests/functional/u/unexpected_special_method_signature.py`

for `variables.py` and `class_checker.py` they're just excluding all the dunder methods from their checks and these two new methods don't really make sense in that context anyway so no need to add those.

2022-03-21 08:06 UTC, DanielNoord approved these changes

2022-03-21 08:45 UTC, Pierre-Sassoulas approved these changes

2022-03-21 08:46 UTC, merged