Remove dead code related to finding the ``pylintrc`` file
PyCQA/pylint pull request #6057
Opened 2022-03-30 15:14 UTC by DanielNoord

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

I wonder if this is considered external. It is in the `__all__` but there is no reason for anybody to use this, I think? We don't even use it as the logic for finding the configuration file has moved to `find_default_config_files`.

2022-03-30 16:04 UTC, Pierre-Sassoulas approved these changes

2022-03-31 07:17 UTC, Pierre-Sassoulas commented
The coverage decreased because there were tests to check that we could browse a python package to find the pylintrc in parent directory too.

I would be in favor of searching at the root of the project in pyproject.toml, setup.cfg, pylintrc and .pylintrc and only that.  It's already a lot more than what flake8 is doing for example.  Guess which project has less issues to handle ? 😄  I think it's the way pylint is used most of the time (or should be used). And we added the possibility to do ``pylint .`` recently.But it's definitely a breaking change and I also think it's contrary to the per-directory configuration that was a big project of @AWhetter. 

This is related to https://github.com/PyCQA/pylint/pull/3769 where they were discussion about configuration.

2022-03-31 07:21 UTC, DanielNoord commented
> The coverage decreased because there were tests to check that we could browse a python package to find the pylintrc in parent directory too.
> 
> I would be in favor of searching at the root of the project in pyproject.toml, setup.cfg, pylintrc and .pylintrc and only that. It's already a lot more than what flake8 is doing for example. Guess which project has less issues to handle ? 😄 I think it's the way pylint is used most of the time (or should be used). And we added the possibility to do `pylint .` recently.But it's definitely a breaking change and I also think it's contrary to the per-directory configuration that was a big project of @AWhetter.
> 
> This is related to #3769 where they were discussion about configuration.

The issue is that these tests don't test that.. I removed these tests because the only asserts are on `find_pylintrc` which we don't use internally.
I have a refactor of `find_default_config_files` ready to go, so I would be more than happy to add similar tests for that function in a follow-up PR.

2022-03-31 07:28 UTC, Pierre-Sassoulas requested changes
I think we should deprecate ``find_pylintrc`` first, before removing in 3.0, it's an API. We can add the new tests in this MR too.

2022-03-31 08:47 UTC, Pierre-Sassoulas approved these changes
Lgtm, thank you.

2022-03-31 09:15 UTC, merged