Total ordering unit test
PyCQA/pylint pull request #6059
Opened 2022-03-30 18:23 UTC by jpy-git

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Closes #6045. Adds a unit test for the `__gt__` method mentioned in the linked issue.
N.B. since we don't currently implement a `__eq__` method (as described in the [docs](https://docs.python.org/3/library/functools.html#functools.total_ordering)) we can't currently assert something like `fake_checker_1 == fake_checker_2` even though they have the same name as args.
Didn't add it in since we're only really doing this for coverage and seems unnecessary, but happy to add in for completeness if desired.

2022-03-30 18:46 UTC, DanielNoord commented on tests/checkers/unittest_base_checker.py
> +def test_base_checker_ordering():
```suggestion
def test_base_checker_ordering() -> None:
    """Test ordering of checkers based on their __gt__ method."""
```

2022-03-30 19:20 UTC, Pierre-Sassoulas requested changes
Let's add the ``__eq__`` we're taking some time for this may as well be exhaustive :)

2022-03-31 01:14 UTC, jpy-git commented
> Let's add the `__eq__` we're taking some time for this may as well be exhaustive :)

I've added in `__eq__` and a test for it 👍 
N.B. since we've added an `__eq__`, I've also had to add the corresponding `__hash__` to make the checkers hashable ([docs](https://docs.python.org/3/reference/datamodel.html#object.__hash__))

2022-03-31 06:24 UTC, Pierre-Sassoulas approved these changes

2022-03-31 06:25 UTC, merged