Fix E1102 false positive
PyCQA/pylint pull request #6068
Opened 2022-03-31 11:04 UTC by tushar-deepsource

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Update E1102 to only be raised when no inferred value is callable.

Resolves #5931

2022-03-31 11:21 UTC, tushar-deepsource commented
https://github.com/PyCQA/pylint/pull/6068/files#diff-9b76776694be02a09ca25a56adee0b3087ad5b86dfafd318923c4bf008c131c3R1233-R1238

This is the part that isn't covered, but it's hard to come up with a case for this, that won't break in the future.

2022-03-31 13:19 UTC, jacobtylerwalls commented on pylint/checkers/typecheck.py
> +                    call_results = list(attr.infer_call_result(node))
Can you place the except directly after this so that the try only wraps what might fail?

2022-04-01 11:48 UTC, srijan-paul commented
zamn :^)

2022-04-01 17:42 UTC, jacobtylerwalls reviewed
nice! one suggestion to loosen this even more.

2022-04-01 17:42 UTC, jacobtylerwalls commented on pylint/checkers/typecheck.py
> +                ):
```suggestion
                if astroid.Uninferable in call_results:
```

2022-04-01 17:42 UTC, jacobtylerwalls commented on pylint/checkers/typecheck.py
> +                    # We were unable to infer return values of the call, skipping
```suggestion
                    # We were unable to infer some return value of the call, skipping
```

2022-04-01 18:05 UTC, jacobtylerwalls commented
Thanks for looking into it. Darn.

I still think long-term we could consider making that change, though. There's no restriction on what you can set with the property. You can set something that's callable, and then `not-callable` becomes sort of wrong. But no one is asking for that change right now :-)

2022-04-01 18:17 UTC, DanielNoord commented
@tushar-deepsource Coming into this pretty late but I was taking a look at stale PRs and found #5593. Could you quickly check if this solves that issue?

2022-04-01 18:46 UTC, tushar-deepsource commented
@DanielNoord This change only affects properties, so no it doesn't solve that issue.

2022-04-01 18:53 UTC, DanielNoord requested changes
Only needs a changelog entry!

Didn't see this was only for `properties`. But that makes sense :)

2022-04-01 18:57 UTC, tushar-deepsource commented
@DanielNoord hopefully this is correct?

2022-04-01 19:00 UTC, DanielNoord approved these changes
Almost 😄 

But thanks @tushar-deepsource! Wonderful fix!

2022-04-01 19:00 UTC, DanielNoord commented on ChangeLog
> +* Only raise ``not-callable`` when all the inferred values of an expression are not callable.
```suggestion
* Only raise ``not-callable`` when all the inferred values of a property are not callable.
```

2022-04-01 19:00 UTC, DanielNoord commented on doc/whatsnew/2.14.rst
> +* Only raise ``not-callable`` when all the inferred values of an expression are not callable.
```suggestion
* Only raise ``not-callable`` when all the inferred values of a property are not callable.
```

2022-04-02 00:02 UTC, jacobtylerwalls commented
Are we moving the changelog entry to 2.13.5?

2022-04-02 06:03 UTC, merged