Fix crash in `c-extension-no-member` check
PyCQA/pylint pull request #6235
Opened 2022-04-08 14:20 UTC by jacobtylerwalls

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #6221. Regression in 129c7302ceaabbbbf41a9872661a3550069b37e3.

- [ ] Add test

2022-04-08 15:31 UTC, Pierre-Sassoulas commented on ChangeLog
> +
```suggestion
```
I think we could add ``Closes #6221`` to the original log for the false negative (#1555 / #5544)

2022-04-08 17:10 UTC, jacobtylerwalls commented
I spent a cycle trying to figure out how to test this. We would need a package with a C extension without ballooning our test dependencies. `coverage` is the package used for that already, but then we need an involved solution to reproduce the inference ambiguity on some element in `coverage`, possibly through inducing an import name collision via another locally installed package (see report, with `leo.core.Qt6` importing names from `Qt6` that might differ from the c extension `Qt6`. It's a bit overwhelming.

2022-04-08 17:35 UTC, Pierre-Sassoulas requested changes
I made a suggestion, we could also post the URL to this comment. I think adding the pragma no cover is important if we're voluntarily not testing the code.

2022-04-08 17:35 UTC, Pierre-Sassoulas commented on pylint/checkers/typecheck.py
> +                    break
```suggestion
                    break   # pragma: no cover
                    # In order to test this, we would need a package with a C extension without ballooning our test 
                    # dependencies. coverage is the package used for that already, but then we need an involved
                    # solution to reproduce the inference ambiguity on some element in coverage, possibly through 
                    # inducing an import name collision via another locally installed package (see report, with 
                    # leo.core.Qt6 importing names from Qt6 that might differ from the c extension Qt6.
```

2022-04-08 20:07 UTC, Pierre-Sassoulas approved these changes

2022-04-08 20:33 UTC, jacobtylerwalls commented
For future reference, here is a test case for `pylint` that fails if `PyQt6` is installed.
```diff
diff --git a/requirements_test.txt b/requirements_test.txt
index 2e35f584..04aac371 100644
--- a/requirements_test.txt
+++ b/requirements_test.txt
@@ -6,6 +6,7 @@ pre-commit~=2.17;python_full_version>="3.6.2"
 tbump~=6.6.0
 contributors-txt>=0.7.3
 pyenchant~=3.2
+PyQt6~=6.2
 pytest-cov~=3.0
 pytest-profiling~=1.7
 pytest-xdist~=2.5
diff --git a/tests/__init__.py b/tests/__init__.py
new file mode 100644
index 00000000..e69de29b
diff --git a/tests/functional/n/no/no_member_c_extension.py b/tests/functional/n/no/no_member_c_extension.py
new file mode 100644
index 00000000..e09f7d03
--- /dev/null
+++ b/tests/functional/n/no/no_member_c_extension.py
@@ -0,0 +1,9 @@
+"""Regression test for https://github.com/PyCQA/pylint/issues/6221"""
+
+# local import that creates ambiguity with test requirement PyQt6
+# PyQt6 has the name printsupport
+from tests.input.qt6 import printsupport
+
+dialog = printsupport.QPrintPreviewDialog
+# paintRequested (nodes.FunctionDef) is the owner of the name connect, not the module
+dialog.paintRequested.connect()
diff --git a/tests/functional/n/no/no_member_c_extension.rc b/tests/functional/n/no/no_member_c_extension.rc
new file mode 100644
index 00000000..b3320786
--- /dev/null
+++ b/tests/functional/n/no/no_member_c_extension.rc
@@ -0,0 +1,2 @@
+[MASTER]
+extension-pkg-allow-list=PyQt6.QtPrintSupport
diff --git a/tests/input/qt6.py b/tests/input/qt6.py
new file mode 100644
index 00000000..44312ea8
--- /dev/null
+++ b/tests/input/qt6.py
@@ -0,0 +1 @@
+from PyQt6 import QtPrintSupport as printsupport
```

2022-04-08 22:44 UTC, jacobtylerwalls commented
Hold up, there's a deeper root cause that's fixable in the astroid brain for qt.

2022-04-08 23:56 UTC, jacobtylerwalls commented
Superseded by https://github.com/PyCQA/astroid/pull/1505

2022-04-08 23:56 UTC, closed without merging

2022-04-09 07:16 UTC, Pierre-Sassoulas commented
But isn't it a good thing that we do not crash in case there's an issue in a brain or in astroid's analysis ?

2022-04-09 13:14 UTC, jacobtylerwalls commented
I guess my thought was that we don't want to silence programming errors. Someone could contribute a broken brain and not realize it if we're just catching errors in pylint.

2022-04-09 13:28 UTC, Pierre-Sassoulas commented
I agree we should not silence our own errors. But on the other hand, the brain was contributed with an error and we have a really hard time reproducing the bug, even adding an automated test to check the fix we added is complicated. What could make sure that we do not contribute faulty brains in the future ?

2022-04-09 13:56 UTC, jacobtylerwalls commented
> Maybe better typing in astroid?

I hear that astroid is not ready for comprehensive type-checking. Maybe we can start turning it on file by file, or just in the brains and work our way toward the center. That's what I'm doing in another library I work on (start on edges).

I added some typing to the astroid PR that will raise mypy errors without the fix.

2022-04-09 14:26 UTC, Pierre-Sassoulas commented
> I hear that astroid is not ready for comprehensive type-checking.

It's closer and closer though.