Added wrong-import-order message example
PyCQA/pylint pull request #6239
Opened 2022-04-08 21:31 UTC by matusvalo

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|     | :bug: Bug fix          |
|     | :sparkles: New feature |
|     | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Closes #5953

2022-04-08 21:36 UTC, matusvalo commented
isort pre-commit hook "fixed" bad.py file causing it is not showing bad case anymore :-(

2022-04-08 21:40 UTC, matusvalo commented
Do we want to exclude isort per file

https://github.com/PyCQA/pylint/blob/0afa5bc5ea8641cce751b8f995fe8ce682f397fa/.pre-commit-config.yaml#L40

or we will exclude whole  `doc/data/messages` directory?

2022-04-09 07:22 UTC, Pierre-Sassoulas commented
> we will exclude whole doc/data/messages directory?

We could exclude all the ``bad.py`` first is the 'exclude' become hard to manage

2022-04-09 14:33 UTC, Pierre-Sassoulas requested changes
Not sure about the regex, I'll revert if it breaks the existing code :)

2022-04-09 14:33 UTC, Pierre-Sassoulas commented on .pre-commit-config.yaml
> +        exclude: doc/data/messages/r/reimported/bad.py|doc/data/messages/w/wrong-import-order/bad.py
```suggestion
        exclude: doc/data/messages/(r/reimported|w/wrong-import-order)/bad.py
```

2022-04-09 14:39 UTC, Pierre-Sassoulas approved these changes
Thank you @matusvalo !

2022-04-09 14:40 UTC, merged