Added logging-fstring-interpolation and logging-format-interpolation message examples'
PyCQA/pylint pull request #6404
Opened 2022-04-19 22:34 UTC by matusvalo

- Added logging-format-interpolation message example
- Added logging-fstring-interpolation message example

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|     | :bug: Bug fix          |
|     | :sparkles: New feature |
|     | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Related #5953

2022-04-20 05:02 UTC, Pierre-Sassoulas requested changes
I think we needs a rationale about the performance implication and why this check exists in the first place (btw, the performance gain are smaller or maybe negligible since f-string were introduced so I don't know what the conclusion should be, I'm personally disabling this check now).

2022-04-27 07:53 UTC, Pierre-Sassoulas approved these changes

2022-04-27 07:53 UTC, Pierre-Sassoulas commented on doc/data/messages/m/logging-format-interpolation/related.rst
> +- `logging variable data <https://docs.python.org/3/howto/logging.html#logging-variable-data>`_
```suggestion
- `logging variable data <https://docs.python.org/3/howto/logging.html#logging-variable-data>`_
- `rational <https://stackoverflow.com/questions/34619790>`_
```

2022-04-27 07:53 UTC, Pierre-Sassoulas commented on doc/data/messages/m/logging-fstring-interpolation/related.rst
> +- `logging variable data <https://docs.python.org/3/howto/logging.html#logging-variable-data>`_
```suggestion
- `logging variable data <https://docs.python.org/3/howto/logging.html#logging-variable-data>`_
- `rational <https://stackoverflow.com/questions/34619790>`_
```

2022-04-27 08:37 UTC, merged

2022-04-28 06:04 UTC, matusvalo commented
Thnank you @Pierre-Sassoulas .