Move `no-self-use` to optional extension
PyCQA/pylint pull request #6448
Opened 2022-04-23 17:29 UTC by cdce8p

## Description
Create new optional extension for `no-self-use` and move check.

Closes #5502

2022-04-23 17:39 UTC, Pierre-Sassoulas approved these changes
Great 👍 The fact that we had so much disable for it in our own code, is proof that it should not be enabled by default. I like that you actually made a standalone checker, independent and fully typed.

2022-04-23 17:40 UTC, Pierre-Sassoulas requested changes
It seems like there's no functional test specific to this check, and the coverage is low for some part. Would you mind recreating a covering functional test ?

2022-05-05 15:47 UTC, Pierre-Sassoulas requested changes

2022-05-05 15:47 UTC, Pierre-Sassoulas commented on doc/whatsnew/2.14.rst
> +* Moved ``no-self-use`` check to optional extension.
```suggestion
* Moved ``no-self-use`` check to optional extension. You now need to explicitly enable this check using
    ``load-plugins=pylint.extensions.no_self_use``.
```

2022-05-05 15:47 UTC, Pierre-Sassoulas commented on ChangeLog
> +* Created ``NoSelfUseChecker`` extension and moved the ``no-self-use`` check.
```suggestion
* Created ``NoSelfUseChecker`` extension and moved the ``no-self-use`` check.
 You now need to explicitly enable this check using ``load-plugins=pylint.extensions.no_self_use``.
```

2022-05-05 15:47 UTC, Pierre-Sassoulas commented on pylint/extensions/no_self_use.py
> +            "be written as a function.",
We need to add an ``old_names`` here.

2022-05-05 15:47 UTC, Pierre-Sassoulas commented on tests/functional/ext/no_self_use/no_self_use.py
> +
```suggestion

    def b(self, /):  # pylint: disable=R0201
        ...
 
```

2022-05-05 16:17 UTC, Pierre-Sassoulas approved these changes
👍

2022-05-05 16:44 UTC, cdce8p commented
> For some reason `duplicate-code` gets triggered on this branch and on some other PRs but not on `main` 😓

Saw that one too. A bit strange tbh. I can't reproduce the warnings locally although they are valid. I've added a disabled comment for the one instance directly caused by this change. This should allow us to move forward with it. The rest can be addressed sometime later.

2022-05-05 16:47 UTC, merged

2022-05-05 17:05 UTC, cdce8p commented
> @cdce8p The CI job still fails. Do you want to do a follow-up to unblock `main`?

I'll open a PR shortly. Interestingly, now `main` also fails. Honestly not sure why it hasn't previously.
https://github.com/PyCQA/pylint/runs/6310323884?check_suite_focus=true#step:9:34