Fix pyenchant with editable pip install
PyCQA/pylint pull request #6462
Opened 2022-04-26 07:53 UTC by Pierre-Sassoulas

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :scroll: Docs          |

## Description

Follow-up to https://github.com/PyCQA/pylint/pull/6440#issuecomment-1109437387

2022-04-26 07:56 UTC, DanielNoord commented
Don't really like this solution as you still need to install stuff outside of the python ecosystem. This still does not allow:
`git clone` + `pip install -e .`. If `C Enchant` was necessary for correct use of `pylint` this would be fine, but to require such dependencies for a simple spelling check feels a bit too much.

I have another solution where we only run the spelling check in CI. I'll create a PR shortly!

2022-04-26 08:08 UTC, Pierre-Sassoulas commented
You're very fast 😄 I changed the approach completely, could you check again. I think this is now the correct approach as this also fix a long standing issue of the spell checker being "hidden". You had to know it existed and you had to install pyenchant yourself and then use the proper option. This does not make a lot of sense.

2022-04-26 08:13 UTC, DanielNoord commented
> You're very fast 😄 I changed the approach completely, could you check again. I think this is now the correct approach as this also fix a long standing issue of the spell checker being "hidden". You had to know it existed and you had to install pyenchant yourself and then use the proper option. This does not make a lot of sense.

The issue remains that doing `pip install pyenchant` will never be enough for `pyenchant` to work. It uses the `C Enchant` library which you need to install manually, for example through home-brew. See https://pyenchant.github.io/pyenchant/install.html#installation.

Therefore, we can't fix this issue without having developers/users go through the extra effort of installing `C Enchant`. For Windows the `pyenchant` documentation even says: `The enchant C library depends on glib2, which poses some interesting challenges.`.
I don't think we should require developers/users to jump through those hoops for a simple spelling check. It is a bit annoying that spelling issues will only surface in CI, but that's kinda what CI is for and since the `Checks` job doesn't take 30 minutes to run PR-submitters won't have to wait too long.

Obviously, we could add something about installing `C Enchant` in our developer documentation and recommend to run with spelling check before submitting PRs, but I don't think it should be standard.

2022-04-26 08:22 UTC, Pierre-Sassoulas commented
I think there's two issues here:
- Adding spelling check in pre-commit
- Adding the extra require for spelling

For spelling check in pre-commit I think it makes sense to add it anyway as a lot of first time contributors do not even run pre-commit locally (As evidenced by the fact that the pre-commit-ci bot very often automatically fix commits). I suppose we don't want to bother the one that do want to install pre-commit. Does the pip install fail if C enchant is not installed ?

Then for the extra require option I think not adding was a real problem as you really have to go out of your way to discover this spell checker.

2022-04-26 08:26 UTC, DanielNoord commented
> I think there's two issues here:
> 
> * Adding spelling check in pre-commit
> * Adding the extra require for spelling
> 
> For spelling check in pre-commit I think it makes sense to add it anyway as a lot of first time contributors do not even run pre-commit locally (As evidenced by the fact that the pre-commit-ci bot very often automatically fix commits). I suppose we don't want to bother the one that do want to install pre-commit. Does the pip install fail if C enchant is not installed ?

Yes, as you would define the dictionary to use in the `rcfile` or command line but that dictionary won't be found because `C Enchant` is not installed. That will result in a crash in the configuration parser.

> Then for the extra require option I think not adding was a real problem as you really have to go out of your way to discover this spell checker.

Adding an extra require option is fine, but the same goes here: it doesn't really work unless you also install `C Enchant` so that should probably be documented there as well.

2022-04-26 08:34 UTC, Pierre-Sassoulas commented
> that dictionary won't be found because C Enchant is not installed. That will result in a crash in the configuration parser.

I noticed that too. I think there might be a better way to handle this in pylint. We could add a hard coded list of choices for the parsing, and then raise a pylint-error message if enchant is not installed later. I did not think a lot about this (and the way we handle the fact that enchant is a schrodinger installation in the SpellingChecker) because there were other issues to fix first. 


> it doesn't really work unless you also install C Enchant so that should probably be documented there as well.

Yeah nothing we can do about it except documenting, but this is an issue for users also imo, not only for pylint's dev.

2022-04-26 08:46 UTC, DanielNoord commented
> > that dictionary won't be found because C Enchant is not installed. That will result in a crash in the configuration parser.
> 
> I noticed that too. I think there might be a better way to handle this in pylint. We could add a hard coded list of choices for the parsing, and then raise a pylint-error message if enchant is not installed later. I did not think a lot about this (and the way we handle the fact that enchant is a schrodinger installation in the SpellingChecker) because there were other issues to fix first. The manual check in pre-commit seems the way to fix this short term 👍
> 
> > it doesn't really work unless you also install C Enchant so that should probably be documented there as well.
> 
> Yeah nothing we can do about it except documenting, but this is an issue for users also imo, not only for pylint's dev.

Another issue I just thought of it is that there is no good way to make sure dictionaries are the same. `Enchant` can get dictionaries from a number of providers so there is no guarantee that my local `en_GB` is the same as your `en_GB`...
That is an additional argument to only let the spelling checker run in CI where we can control the dictionary to be used.

2022-04-26 12:50 UTC, DanielNoord requested changes

2022-04-26 13:47 UTC, Pierre-Sassoulas commented on README.rst
> +code with pytest_, (pytest-cov_) and your local python version::
I guess it means pytest-cov is optional (to get coverage)

2022-04-28 08:24 UTC, DanielNoord approved these changes

2022-04-28 08:24 UTC, DanielNoord commented on ChangeLog
> +  This will requires a local installation of ``pyenchant``. You will still need to install the
```suggestion
  This will add ``pyenchant`` to pylint's dependencies. You will still need to install the
```

2022-04-28 08:24 UTC, DanielNoord commented on README.rst
> +code with pytest_, (pytest-cov_) and your local python version::
```suggestion
code with pytest_ and your local python version::
```

I'd say let's remove it here. It is not totally clear what users should do.

2022-04-28 08:24 UTC, DanielNoord commented on doc/whatsnew/2.14.rst
> +  This will requires a local installation of ``pyenchant``. You will still need to install the
```suggestion
  This will add ``pyenchant`` to pylint's dependencies. You will still need to install the
```

2022-04-28 11:09 UTC, merged