Added try-except-raise message example
PyCQA/pylint pull request #6540
Opened 2022-05-07 17:50 UTC by matusvalo

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|     | :bug: Bug fix          |
|     | :sparkles: New feature |
|     | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Related #5953

2022-05-07 19:22 UTC, jacobtylerwalls commented
Thanks. Is `details.rst` a good place to summarize the discussion from https://github.com/PyCQA/pylint/issues/5884#issuecomment-1064310365 involving filtering exceptions?

2022-05-07 19:33 UTC, Pierre-Sassoulas requested changes
I agree that we should add a detail.rst, to be clear that there's a legitimate use case for re raising immediately but that this check is smart enough to not have a false positive for it. 

I.e. with the following inheritance tree:
```
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
```

```python      
try:
    some_calculation(...)
except ZeroDivisionError as e:
    raise
except ArithmeticError:
   pass
```   
will not raise because ZeroDivisionError  inherit from ArithmeticError.

2022-05-07 19:33 UTC, Pierre-Sassoulas commented on doc/data/messages/t/try-except-raise/bad.py
> +    raise
```suggestion
try:
    1 / 0
except ZeroDivisionError as e:  # [try-except-raise]
    raise
```

2022-05-07 19:33 UTC, Pierre-Sassoulas commented on doc/data/messages/t/try-except-raise/good.py
> +    raise ValueError from e
```suggestion
# The try except might be remove entirely:
1 / 0

# Or another more detailed exception can be raised:
try:
    1 / 0
except ZeroDivisionError as e:
    raise ValueError("The area of the rectangle cannot be zero") from e
```

2022-05-08 13:30 UTC, jacobtylerwalls commented on doc/data/messages/t/try-except-raise/good.py
> +# The try except might be remove entirely:
```suggestion
# The try except might be removed entirely:
```

2022-05-09 09:39 UTC, matusvalo commented
Added details.rst. Please review if now it is OK.

2022-05-09 10:29 UTC, Pierre-Sassoulas approved these changes
👍

2022-05-09 10:30 UTC, merged