Suppress useless-super-delegation on __hash__ in classes with __eq__
PyCQA/pylint pull request #6611
Opened 2022-05-13 21:00 UTC by timmartin

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

If a class overrides `__eq__` then we should allow trivial overrides of `__hash__` without issuing a `useless-super-delegation` warning, because the override can be significant.

As explained in the Python docs:
> A class that overrides `__eq__` and does not define `__hash__` will have its `__hash__()` implicitly set to `None`. When the
> `__hash__` method of a class is None, instances of the class will raise an appropriate `TypeError` when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking `isinstance(obj, collections.abc.Hashable)`.

Closes #3934

2022-05-14 13:34 UTC, DanielNoord requested changes
Thanks for working on this!

I made comments on the new method before I saw you just copied what was already there. Perhaps you can't make the comment better, but using `safe_infer` would be good. We would fix a long standing bug and improve our code coverage in one PR 🎉

2022-05-14 13:34 UTC, DanielNoord commented on pylint/checkers/classes/class_checker.py
> +        # With decorators is a change of use
I'm not sure I understand what you mean with this comment. Could you be a little bit more specific?

2022-05-14 13:34 UTC, DanielNoord commented on pylint/checkers/classes/class_checker.py
> +        # Doing something else than what we are interested into.
```suggestion
        # Doing something else than what we are interested in.
```

2022-05-14 13:34 UTC, DanielNoord commented on pylint/checkers/classes/class_checker.py
> +        super_call = next(call.func.expr.infer())
Can you use `safe_infer` here?

2022-05-14 13:34 UTC, DanielNoord commented on pylint/checkers/classes/class_checker.py
> +    def _check_useless_super_delegation(self, function: nodes.FunctionDef):
```suggestion
    def _check_useless_super_delegation(self, function: nodes.FunctionDef) -> None:
```

2022-05-15 19:41 UTC, DanielNoord approved these changes

2022-05-15 21:37 UTC, Pierre-Sassoulas approved these changes
👍

2022-05-15 21:37 UTC, merged