[refactor] Make sure we have the expected typing in visitors
PyCQA/pylint pull request #6892
Opened 2022-06-08 11:46 UTC by Pierre-Sassoulas

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Refs https://github.com/PyCQA/pylint/pull/6636#discussion_r891485685

2022-06-08 13:03 UTC, cdce8p requested changes
I would recommend to limit this refactoring to the suggestion in https://github.com/PyCQA/pylint/pull/6636#discussion_r891485685. All other changes aren't worth it IMO.

2022-06-09 03:04 UTC, Pierre-Sassoulas commented
I checked for all the call of a visitor function directly (``self.visit_``) and added the typing for them.

2022-06-09 12:18 UTC, cdce8p approved these changes
Looks good. One last comment, can be merged after that

2022-06-09 12:20 UTC, cdce8p commented on pylint/extensions/broad_try_clause.py
> +                f" most {self.linter.config.max_try_statements}."
```suggestion
                f" most {self.linter.config.max_try_statements}"
```
The trailing `.` is causing the CI failure.

2022-06-12 18:05 UTC, Pierre-Sassoulas commented on pylint/extensions/docparams.py
> +    def visit_yield(self, node: nodes.Yield | nodes.YieldFrom) -> None:
Nice catch !

2022-06-12 19:06 UTC, merged