Rename ``useless-super-delegation`` to ``useless-parent-delegation``
PyCQA/pylint pull request #6955
Opened 2022-06-15 08:03 UTC by Pierre-Sassoulas

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Refs #6953

2022-06-15 08:09 UTC, Pierre-Sassoulas commented on pylint/checkers/classes/class_checker.py
> +        {"old_names": [("W0235", "useless-super-delegation")]},
Using a tuple here trip up the check for ``consider-using-namedtuple-or-dataclass`` for the whole dict.

2022-06-15 21:57 UTC, DanielNoord requested changes

2022-06-15 21:57 UTC, DanielNoord commented on pylint/checkers/classes/class_checker.py
> +        "Useless parent delegation in method %r",
```suggestion
        "Useless parent or super() delegation in method %r",
```

2022-06-15 21:57 UTC, DanielNoord commented on pylint/checkers/classes/class_checker.py
> +        "relying on parent delegation to do the same thing as another method "
```suggestion
        "relying on parent or super() delegation to do the same thing as another method "
```

2022-06-15 21:57 UTC, DanielNoord commented on tests/functional/u/useless/useless_super_delegation.py
> +    def equivalent_params(self): # [useless-parent-delegation]
We should probably rename all test files.

2022-06-24 08:30 UTC, DanielNoord approved these changes

2022-06-24 08:33 UTC, merged