Add `hidden-parent-method` message
PyCQA/pylint pull request #7007
Opened 2022-06-23 00:12 UTC by jacobtylerwalls

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description
Adds new refactoring message `hidden-parent-method`.

When the behavior of a method happens to depend on the order of the direct parents of a class (left-to-right in `Class A(left, right)`), then the code can yield potentially surprising results by hiding the method on the subsequent parent: better to explicitly reimplement the behavior or to create a single ancestor with the desired behavior.

Fixes #6992

2022-07-02 23:18 UTC, jacobtylerwalls commented
This should probably be an extension!

2022-07-03 05:52 UTC, Pierre-Sassoulas requested changes
This look pretty good ! It's always safer to put a new check in extension, but I think this is a very valuable check so I think we could add it to the default checks, I'll add the need decision label regarding this.

2022-07-03 05:52 UTC, Pierre-Sassoulas commented on doc/data/messages/o/order-dependent-resolution/bad.py
> +        return "Don't do that!"
```suggestion
class EmotionalBlackmailingParent:
    @staticmethod
    def scold():
        return "If you do that, mommy won't love you anymore !"
```

This is not a real suggestion. Great example, the possibility are endless !! 😄

2022-07-03 05:52 UTC, Pierre-Sassoulas commented on pylint/checkers/design_analysis.py
> +        "super() called despite multiple direct parents defining %s",
```suggestion
        "super() called despite %s defining %s",
```
...despite 'HarshParent', 'SomeClass' and  'KindParent' defining... The more info we add to the actual message the less confusing it is for someone who don't initially know what order dependent resolution is.

2022-07-03 05:52 UTC, Pierre-Sassoulas commented on pylint/checkers/design_analysis.py
> +        for parent_meth in methods_defined_in_multiple_bases:
Now, we also have the meth user parent 😱 ?

```python
class MethParent:
    @staticmethod
    def scold():
        return "Don't do that, do meth."
```

2022-07-03 05:52 UTC, Pierre-Sassoulas commented on tests/functional/s/super/super_checks.py
> +        super(Child, self).method()  # [order-dependent-super-resolution]
I'm not surprised the Alabama cousin would have issue.

2022-07-03 05:52 UTC, Pierre-Sassoulas commented on pylint/checkers/design_analysis.py
> +            )
```suggestion
        if missing_reimplementations:
            functions = ", ".join(sorted(f.name for f in missing_reimplementations))
            classes = ", ".join(b.name for b in node.bases)
            self.add_message(
                "order-dependent-resolution",
                node=node,
                args=(classes, functions),
                confidence=INFERENCE,
            )
```
(Untested but it should work ?)

2022-07-04 14:22 UTC, jacobtylerwalls commented
> This is unlikely to have been caused by your changes.

This was definitely caused by my changes 😄

2022-07-04 14:54 UTC, Pierre-Sassoulas commented
>This was definitely caused by my changes

Yeah I realized that and deleted the message 😄 

The primer seems to have a real problem now though.

2022-07-04 20:52 UTC, jacobtylerwalls commented
Well, we may be on the hook anyway for dealing with all-paths-delegating-to-super based on the last test case I thought of. Rats. Back to work in progress.

2022-07-31 13:35 UTC, jacobtylerwalls commented on tests/functional/h/hidden_parent_method.py
> +class Granchild2(Child6, Child7):
```suggestion
class Grandchild2(Child6, Child7):
```

2022-10-09 03:42 UTC, closed without merging

2022-10-10 06:09 UTC, DanielNoord commented
@jacobtylerwalls Is this unfixable?

2022-10-10 11:00 UTC, jacobtylerwalls commented
Perhaps. Needs more analysis.