Fix tests for Python 3.11, don't emit `super-init-not-called` for `Enum` subclasses
PyCQA/pylint pull request #7167
Opened 2022-07-11 23:23 UTC by AdamWill

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

This fixes some issues in the tests with Python 3.11, and makes one change to the actual checks that is exposed by Python 3.11 - not emitting `super-init-not-called` for subclasses of `Enum`. `Enum` has a `__init__` in Python 3.11, but it does nothing at all (just `pass`), and the examples in Python's own `Enum` docs include sample subclasses with their own `__init__` which do not call `Enum.__init__`, so clearly it's OK/intended for you to do that. I've [asked upstream why this useless `Enum.__init__` was added at all](https://github.com/python/cpython/pull/30582#issuecomment-1181055042).

2022-07-11 23:26 UTC, AdamWill commented
Note, this is my first time touching pylint so please review carefully! There is still a problem with the `syntax_error` and `import_error` tests, discussed somewhat at https://github.com/PyCQA/pylint/pull/6551#issuecomment-1180893393 and replies - I wasn't able to come up with a sensibly upstreamable fix for that.

2022-07-12 06:29 UTC, DanielNoord requested changes
Let's wait for a response on the `CPython` issue. I'd like to know if this is a conscious decision.

2022-07-12 06:29 UTC, DanielNoord commented on tests/functional/i/iterable_context_asyncio.py
> +coroutines built with asyncio.coroutine.
```suggestion
coroutines built with asyncio.coroutine.

These decorators were deprecated in 3.8 and removed in 3.10.
```

2022-07-12 06:29 UTC, DanielNoord commented on tests/functional/a/access/access_attr_before_def_false_positive.py
> +# pylint: disable=useless-object-inheritance,too-few-public-methods deprecated-module
```suggestion
# pylint: disable=useless-object-inheritance,too-few-public-methods, deprecated-module
```

2022-07-12 06:29 UTC, DanielNoord commented on doc/whatsnew/2/2.15/index.rst
> +* Don't report ``super-init-not-called`` for subclasses of ``Enum`` (on Python >= 3.11).
This should probably be moved so the `Closes` is not associated with it.

2022-07-12 07:22 UTC, Pierre-Sassoulas commented on doc/whatsnew/2/2.15/index.rst
>  * Don't report ``unsupported-binary-operation`` on Python <= 3.9 when using the ``|`` operator
```suggestion
* Don't report ``super-init-not-called`` for subclasses of ``Enum`` (on Python >= 3.11).


* Don't report ``unsupported-binary-operation`` on Python <= 3.9 when using the ``|`` operator
```

2022-07-12 07:22 UTC, Pierre-Sassoulas commented on doc/whatsnew/2/2.15/index.rst
> +
```suggestion
```

2022-07-12 07:50 UTC, Pierre-Sassoulas approved these changes
👍

2022-07-12 19:43 UTC, AdamWill commented
I've re-factored the review changes into the original commits, and added a couple more fixes, including one for the syntax-error problem. In https://github.com/PyCQA/pylint/pull/6551 @DanielNoord suggested moving that test into the unit tests, but this just seems easier, at least until they change the description of *this* syntax error too...

2022-07-12 19:45 UTC, AdamWill commented
The CI failures look to be problems in the CI infra, not in the PR.

2022-07-13 18:56 UTC, AdamWill commented
@DanielNoord done, can you clear the 'change requested'?

2022-07-13 21:59 UTC, DanielNoord approved these changes
Made a mistake in my previous comment... 😅 

Thanks @AdamWill

2022-07-13 21:59 UTC, DanielNoord commented on tests/functional/i/iterable_context_asyncio.py
> +These decorators were deprecated in 3.8 and removed in 3.10.
```suggestion
These decorators were deprecated in 3.8 and removed in 3.11.
```

2022-07-13 22:00 UTC, merged