handle no-member false positive for generators
PyCQA/pylint pull request #7505
Opened 2022-09-20 16:12 UTC by clavedeluna

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |

## Description

A false positive for when a generator called internal enter / exit methods was reported. This PR handles this case in the same way other outlier cases are handled, by adding code to detect this is a generator.

Closes #2567

2022-09-20 16:13 UTC, clavedeluna commented on tests/functional/n/no/no_member_generators.py
> +cm.__exit__(None, None, None)
There is no corresponding .txt file because no pylint errors or warnings should be in the output.

2022-09-20 21:06 UTC, Pierre-Sassoulas approved these changes
LGTM, thank you for the fix. (Another possibility would be to make astroid understands decorator better but this is a lot harder to do). I'm going to wait for Daniel's opinion before merging.

2022-09-21 11:04 UTC, DanielNoord requested changes
This should indeed be fixed in `astroid`.

Specifically by changing `GeneratorModel` which gets used by `bases.Generator` here:
https://github.com/PyCQA/astroid/blob/849d043f3e3cd63881ba919ccba4e6a726947d22/astroid/bases.py#L606

You can find `astroid.interpreter.objectmodel.GeneratorModel` here:
https://github.com/PyCQA/astroid/blob/849d043f3e3cd63881ba919ccba4e6a726947d22/astroid/interpreter/objectmodel.py#L601

We would need to add `attr___enter__` and `attr___exit__`. It should be relatively straightforward to do so. We only need to make sure that we get the typing and arguments that can be passed to these methods correctly.
The signature of these methods can be found here:
https://docs.python.org/3/reference/datamodel.html#object.__enter__

2022-09-21 13:58 UTC, clavedeluna commented
> This should indeed be fixed in `astroid`.

happy to do it. I've followed your instructions and started [this draft PR](https://github.com/PyCQA/astroid/pull/1803) but I'm hoping you can help me fill in the methods as I'm not too sure what they should be....

2022-09-29 11:55 UTC, closed without merging