bugfix for Attribute.attrname
PyCQA/pylint pull request #7541
Opened 2022-09-29 16:11 UTC by clavedeluna

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Add functional test that demonstrates we forgot to correctly call the `attrname` attribute for an Attribute node. This fixes that.
Could potentially do some refactoring because we do this operation three times
```
            if isinstance(iter_obj, nodes.Attribute):
                obj_name = iter_obj.attrname
            else:
                obj_name = iter_obj.name
```
but the downside would be passing in as an argument. It could be best to leave as is in some cases.

Closes #7528

2022-09-29 19:03 UTC, Pierre-Sassoulas requested changes
LGTM, thank you. I opened https://github.com/PyCQA/astroid/issues/1811 in astroid, because this problem happens A LOT.

2022-09-29 19:03 UTC, Pierre-Sassoulas commented on doc/whatsnew/fragments/7528.bugfix
> +Fix bug in getting name attribute from Attribute node.
```suggestion
Fixed a crash of the ``modified_iterating`` checker when iterating on a set defined as a class attribute.
```

2022-09-30 10:41 UTC, DanielNoord requested changes

2022-09-30 10:41 UTC, DanielNoord commented on tests/functional/m/modified_iterating.py
> +# pylint: disable=not-callable,unnecessary-comprehension,too-few-public-methods, missing-class-docstring, missing-function-docstring
```suggestion
# pylint: disable=not-callable,unnecessary-comprehension,too-few-public-methods,missing-class-docstring,missing-function-docstring
```

I don't have a preference for white spaces after comma's in a disable comment, but let's follow the pre-existing style.

2022-09-30 10:42 UTC, DanielNoord approved these changes

2022-09-30 11:11 UTC, Pierre-Sassoulas approved these changes

2022-09-30 11:11 UTC, merged