Add docs for various `invalid-*` messages
PyCQA/pylint pull request #7606
Opened 2022-10-11 12:28 UTC by clavedeluna

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

Add docs examples for various `invalid-*` messages

Refs #5953

2022-10-11 19:29 UTC, Pierre-Sassoulas requested changes
Thank you !  I'm jst trying to avoid Foo/Bar/FooBar and boring one letter name. I often try to have fruit and animals in example so it's more "lively". Other example could work too, let me know if it make no sense. Admittedly I did not find the use case for changing ``__class__`` live so it might be off..

2022-10-11 19:29 UTC, Pierre-Sassoulas commented on doc/data/messages/i/invalid-class-object/bad.py
> +A.__class__ = 1  # [invalid-class-object]
```suggestion
class Apple:
    pass


Apple.__class__ = 1  # [invalid-class-object]
```

2022-10-11 19:29 UTC, Pierre-Sassoulas commented on doc/data/messages/i/invalid-class-object/good.py
> +A.__class__ = B
```suggestion
class Apple:
    pass


class RedDelicious:
    pass


Apple.__class__ = RedDelicious
```

2022-10-11 21:07 UTC, clavedeluna commented
Github's batch commit feature must be down temporarily 🤔

2022-10-12 07:05 UTC, Pierre-Sassoulas approved these changes
👌

2022-10-12 07:06 UTC, merged