Fix a false negative for ``unused-import``
PyCQA/pylint pull request #7621
Opened 2022-10-14 07:35 UTC by mbyrnepr2

Fix a false negative for ``unused-import`` when linting multiple modules & one module uses an import in a type annotation & the same import is unused in a subsequent module.

Closes #4150

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |

## Description

Closes #XXXX

2022-10-15 12:47 UTC, Pierre-Sassoulas approved these changes
Great fix !

2022-10-15 12:47 UTC, Pierre-Sassoulas commented on doc/whatsnew/fragments/4150.false_negative
> +Fix a false negative for ``unused-import`` when linting multiple modules & one module uses an import in a type annotation & the same import is unused in a subsequent module.
```suggestion
Fix a false negative for ``unused-import`` when one module used an import in a type annotation that was also used in another module.
```

2022-10-15 12:47 UTC, Pierre-Sassoulas commented on pylint/checkers/variables.py
> +        self._type_annotation_names = []
The fix itself is really simple 😄

2022-10-15 12:49 UTC, Pierre-Sassoulas commented
Not sure about what to do regarding the release we're aiming. It's a bug but at the same time it was a false negative. Maybe 2.16.0 so we do not raise new messages in a patch. If there's an oversight on our side we don't want cascading patches backport ?

2022-10-15 13:14 UTC, mbyrnepr2 commented
> Not sure about what to do regarding the release we're aiming. It's a bug but at the same time it was a false negative. Maybe 2.16.0 so we do not raise new messages in a patch. If there's an oversight on our side we don't want cascading patches backport ?

Agreed. Happy to wait until 2.16.0.

2022-10-15 13:16 UTC, mbyrnepr2 commented
About the primer [comment](https://github.com/PyCQA/pylint/pull/7621#issuecomment-1278650827). 

I notice that the output for Django, Pandas & Sentry is similar to some other open MRs; it doesn't look like it is caused by this MR.
The black output looks relevant to this MR but, at the same time, it is saying that a new message is emitted while I also see that message emitted on main.

2022-10-15 20:09 UTC, Pierre-Sassoulas commented
In black I think ``os`` is used here : https://github.com/psf/black/blob/f16333e78ba77ab29ab0b75e10891e6c65c6da7e/src/blib2to3/pgen2/pgen.py#L25. Feel like a false positive.

2022-10-15 21:17 UTC, mbyrnepr2 commented
> In black I think `os` is used here : https://github.com/psf/black/blob/f16333e78ba77ab29ab0b75e10891e6c65c6da7e/src/blib2to3/pgen2/pgen.py#L25. Feel like a false positive.

I agree with you & I'm happy to dig into that one; but this false positive isn't created by the current MR.

The sample from the `black` primer will fail on `main` also:
```python
import os
from typing import Union
Path = Union[str, "os.PathLike[str]"]
```

2022-10-16 07:44 UTC, Pierre-Sassoulas commented
> I agree with you & I'm happy to dig into that one; but this false positive isn't created by the current MR.

Ha, something is wrong with the primer then, sorry.

2022-10-29 11:50 UTC, jacobtylerwalls approved these changes

2022-10-29 12:18 UTC, Pierre-Sassoulas requested changes
@mbyrnepr2 can you merge or rebase on main so we launch the new python 3.11 tests please ?

2022-10-29 15:44 UTC, Pierre-Sassoulas approved these changes

2022-10-29 15:45 UTC, merged

2022-10-30 20:41 UTC, DanielNoord commented
@mbyrnepr2 The message in `black` seems like a false positive?

2022-10-30 20:58 UTC, mbyrnepr2 commented
It does seem that way, I agree @DanielNoord but we can also see the same happening on the main branch (before it was merged). Perhaps an issue with the primer?

2022-10-30 20:59 UTC, DanielNoord commented
Probably! Went through my notifications of last week and noticed this message, but `pytest` is also broken in that comment so could very well be a fluke.