Add new `feature` category for changelog
PyCQA/pylint pull request #7659
Opened 2022-10-21 11:56 UTC by cdce8p

## Description
At the moment, there isn't a good category for new features which aren't checks.
The next best option would be `other` but that doesn't seem quite right.

Refs: https://github.com/PyCQA/pylint/issues/7362

2022-10-21 18:17 UTC, Pierre-Sassoulas submitted a review, later dismissed
I think it makes sense, I also noticed that 👍

2022-10-21 19:18 UTC, DudeNr33 requested changes
Looks good to me, when `contribute.rst` is updated as well it can be merged. 👍

2022-10-21 19:18 UTC, DudeNr33 commented on .github/PULL_REQUEST_TEMPLATE.md
> +  new_check, removed_check, extension, false_positive, false_negative, bugfix, other, internal.
This section is also in [contribute.rst](https://github.com/PyCQA/pylint/blob/main/doc/development_guide/contributor_guide/contribute.rst), so we'd need to add this there as well.

2022-10-22 07:59 UTC, Pierre-Sassoulas approved these changes

2022-10-22 08:01 UTC, Pierre-Sassoulas commented
Sorry @DudeNr33 I was forced to re-request review to be able to merge :)

2022-10-22 10:29 UTC, cdce8p commented
> Sorry @DudeNr33 I was forced to re-request review to be able to merge :)

@Pierre-Sassoulas Usually we should be able to dismiss the review. I don't seem to be able to either though 🤔
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/dismissing-a-pull-request-review

2022-10-22 10:38 UTC, Pierre-Sassoulas commented
>  I don't seem to be able to either though 

Yeah, same here, I don't know why.

2022-10-22 10:49 UTC, cdce8p commented
> > I don't seem to be able to either though
> 
> Yeah, same here, I don't know why.

From the Github [docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-pull-request-reviews-before-merging)

> Optionally, you can restrict the ability to dismiss pull request reviews to specific people or teams. For more information, see "[Dismissing a pull request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/dismissing-a-pull-request-review)."

--
Just FYI I enabled `Always suggest updating pull request branches` in the repo settings to suggest the `Update branch` button. Usually with towncrier we shouldn't need to use it but it can be helpful sometimes anyway.

2022-10-22 12:11 UTC, DudeNr33 approved these changes
Sorry for the delay!

2022-10-22 12:11 UTC, merged