add test and expl for line-too-long useless-supp FP
PyCQA/pylint pull request #7887
Opened 2022-12-02 11:45 UTC by clavedeluna

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

Closes #3368

2022-12-02 12:03 UTC, Pierre-Sassoulas requested changes
Some wording, and I think it's better to xfail the expected behavior rather than crystalize the wrong behavior

2022-12-02 12:03 UTC, Pierre-Sassoulas commented on tests/test_self.py
> +
```suggestion
    @pytest.mark.xfail(reason="See https://github.com/PyCQA/pylint/issues/3368")
    def test_line_too_long_useless_suppression(self) -> None:
        module = join(HERE, "data", "line_too_long_no_code.py")
        self._test_output([module, "--enable=all"], expected_output="")

```

2022-12-02 12:03 UTC, Pierre-Sassoulas commented on tests/data/line_too_long_no_code.py
> +# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789  # pylint: disable=line-too-long
```suggestion
# ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789  # pylint: disable=line-too-long
# See https://github.com/PyCQA/pylint/issues/3368
```

2022-12-02 19:56 UTC, DanielNoord commented
> Some wording, and I think it's better to xfail the expected behavior rather than crystalize the wrong behavior

Isn't the issue here that we can't know for sure that the `xfail` is because of the original reason? If we break something else the test will still fail. I like documenting the poor behaviour, even though it is not perfect. At least that way we know what is/was expected behaviour rather than "something in this test will fail".

2022-12-02 20:13 UTC, DanielNoord commented
> Sure, in theory something else could fail, but this is a one line file with only the example, I think we're safe. There's a lot of time where we asked ourselves why something "obviously" wrong was in the functional tests.

Can't we add:
```python
# This test serves mostly to document current behaviour.
# If you manage to make it fail and remove the useless-suppression
# warning please contact Daniel to get your
# celebratory reward (and well done 👍🏻)
```

2022-12-02 20:17 UTC, Pierre-Sassoulas commented
Sounds great, what's the reward going to be though ? 😄

2022-12-02 20:19 UTC, DanielNoord commented
10 internet points, a beer if they ever meet me in person and an extra speedy review of a PR of choice.
Who wouldn't want to cash in that reward?

2022-12-02 21:01 UTC, clavedeluna commented
> Sounds great, what's the reward going to be though ? 😄

Are you agreeing to keeping the original test, so I can revert the latest commit, correct?

2022-12-02 21:04 UTC, Pierre-Sassoulas commented
Sure !

2022-12-03 08:20 UTC, Pierre-Sassoulas approved these changes

2022-12-03 08:21 UTC, merged