Fixes ``method-cache-max-size-none`` false positive
PyCQA/pylint pull request #7908
Opened 2022-12-07 19:58 UTC by clavedeluna

…iting from ``Enum``.

Closes #7857

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #7857

2022-12-08 20:57 UTC, Pierre-Sassoulas requested changes
Thank you, I liked the refactor too 👍 (Could you rebase on latest main please, the enchant issue was fixed in #7910)

2022-12-08 22:10 UTC, DanielNoord approved these changes

2022-12-09 14:05 UTC, Pierre-Sassoulas commented on pylint/checkers/stdlib.py
> +            # method of class inheriting from Enum is excempt from this check.
```suggestion
            # method of class inheriting from Enum is exempt from this check.
```

2022-12-09 14:05 UTC, Pierre-Sassoulas approved these changes

2022-12-09 14:06 UTC, merged

2022-12-09 14:48 UTC, Pierre-Sassoulas commented
Moving to 2.16.0 because I don't want to fix the cherry-pick conflict.