Invalid argument exit code
PyCQA/pylint pull request #7931
Opened 2022-12-12 23:37 UTC by dmrlawson

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

We were bitten by this causing us to think that pylint was completing successfully when in fact a typo in a configuration file was causing argparse to exit with exit code 2. This didn't happen in older versions of pylint for whatever reason. The [documentation for pylint](https://pylint.pycqa.org/en/latest/user_guide/usage/run.html#exit-codes) suggests that this means "error message issued" but that pylint executed properly when this is not the case.

It feels a bit clumsy to just add in `try..except`, but on the other hand it's perhaps unexpected that argpase will raise a `SystemExit`. I'm open to any suggestions to improve this.

2022-12-13 08:09 UTC, Pierre-Sassoulas reviewed
Nice catch, we indeed missed that argparse could exit with its own exit code and the inconsistency with pylint's error codes. I think we should use -1 because it's the only way our bit encoded error code can be extended to 64 if required. Thoughts @DanielNoord ?

2022-12-14 09:51 UTC, dmrlawson commented
> Nice catch, we indeed missed that argparse could exit with its own exit code and the inconsistency with pylint's error codes. I think we should use -1 because it's the only way our bit encoded error code can be extended to 64 if required. Thoughts @DanielNoord ?

`sys.exit(32)` appears throughout the code. The "usage error" exit code could be factored out to be a constant and then changed but it's a bit more than I was intending here.

```
$ grep -r 'sys.exit(32)'
pylint/pyreverse/utils.py:        sys.exit(32)
pylint/pyreverse/utils.py:        sys.exit(32)
pylint/lint/run.py:            sys.exit(32)
pylint/lint/run.py:            sys.exit(32)
pylint/lint/run.py:            sys.exit(32)
pylint/lint/run.py:                sys.exit(32)
pylint/config/arguments_manager.py:            sys.exit(32)
pylint/config/config_initialization.py:        sys.exit(32)
pylint/config/config_initialization.py:            sys.exit(32)
```

2022-12-14 12:37 UTC, Pierre-Sassoulas commented
You're right let's keep it as 32, I wasn't up to date on this aspect of the code sorry.

2022-12-14 19:22 UTC, DanielNoord submitted a review, later dismissed

2022-12-14 19:35 UTC, Pierre-Sassoulas requested changes
Could you fix the tests (there's some other test that is somewhat fragile you'll need to add the new file to it) and add a changelog entry please ?

2022-12-14 22:07 UTC, Pierre-Sassoulas submitted a review, later dismissed
Great job 👌

2022-12-14 22:07 UTC, Pierre-Sassoulas commented on doc/whatsnew/fragments/7931.bugfix
> +Fix exit code when argparse raises SystemExit due to bad arguments.
```suggestion
When pylint exit due to bad arguments being provided the exit code will now be the expected ``32``.
```

2022-12-14 22:07 UTC, Pierre-Sassoulas approved these changes

2022-12-14 22:24 UTC, merged