class attrs should not emit assigning-non-slot msg
PyCQA/pylint pull request #7987
Opened 2022-12-26 13:14 UTC by clavedeluna

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Pylint was raising  ``assigning-non-slot`` when a class attribute was re-assigned, which I believe is incorrect given that `__slots__` is meant for instance attrs.

Closes #6001

2022-12-27 08:11 UTC, DanielNoord requested changes
Let's add `INFERENCE` confidence while we're here.

Also, could you add the example from the issue just to be sure?

Rest LGTM!

2022-12-27 08:41 UTC, Pierre-Sassoulas submitted a review, later dismissed

2022-12-27 11:42 UTC, DanielNoord requested changes

2022-12-27 11:42 UTC, DanielNoord commented on tests/functional/a/assigning/assigning_non_slot.py
> +        self.__class__ = ClassWithSlots
This feels incorrect upon second review. This is an instance attribute and should still flag right?

2022-12-27 19:59 UTC, Pierre-Sassoulas commented
I think we need an actual rebase on main to see the real codecov result @DanielNoord

2022-12-27 20:07 UTC, DanielNoord commented
> I think we need an actual rebase on main to see the real codecov result @DanielNoord

Yeah, sadly. Oh well, that's a small price to pay.

Sorry for the churn @clavedeluna, you'll need to rebase to get CI to pass :smile:

2022-12-29 21:19 UTC, DanielNoord commented
Is the test failure genuine?

2022-12-29 21:29 UTC, Pierre-Sassoulas commented
I swear the latest pypy 3.8 release is nothing but trouble :(

2022-12-29 21:43 UTC, DanielNoord requested changes
Small nits 😄

2022-12-29 21:43 UTC, DanielNoord commented on pylint/checkers/classes/class_checker.py
>              return
```suggestion
            return

```

2022-12-29 21:43 UTC, DanielNoord commented on tests/functional/a/assigning/assigning_non_slot.py
> +        self.__class__ = ClassWithSlots  # [assigning-non-slot]
```suggestion
        self.__class__ = ClassWithSlots  # [assigning-non-slot]
        self.test  # [assigning-non-slot]
```

2022-12-30 14:53 UTC, DanielNoord approved these changes

2022-12-30 15:26 UTC, merged

2022-12-30 21:05 UTC, DanielNoord commented
@clavedeluna Do you want to try this back port yourself?