Remove deprecated functions and classes
PyCQA/pylint pull request #8409
Opened 2023-03-08 22:18 UTC by DanielNoord

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

We're getting there.

2023-03-08 22:37 UTC, Pierre-Sassoulas requested changes
We need to explain what's the alternative, for example "To make a checker reduce map data simply implement get_map_data and reduce_map_data." etc. etc. (We can copy paste from the deprecation message and adapt).

2023-03-08 22:37 UTC, Pierre-Sassoulas commented on doc/whatsnew/fragments/8409.breaking
> +``get_python_paht``, ``fix_import_path`` and ``get_global_option``.
```suggestion
``get_python_path``, ``fix_import_path`` and ``get_global_option``.
```

2023-03-08 22:38 UTC, DanielNoord commented
> We need to explain what's the alternative, for example "To make a checker reduce map data simply implement get_map_data and reduce_map_data." etc. etc. (We can copy paste from the deprecation message and adapt).

I was wondering about that. It feels as if the changelog can become very long. Shouldn't we just refer to the code and let the old `DeprecationWarnings` show what needs to be changed?

2023-03-08 22:42 UTC, Pierre-Sassoulas commented
Yeah it's going to be long but it's the place where people are going to look first when something break, so it needs to explain what to do imo (also if someone is taking care of the deprecation warnings they won't need it).

2023-03-09 09:39 UTC, Pierre-Sassoulas approved these changes

2023-03-09 10:30 UTC, DanielNoord commented
But docs fail :(

2023-03-09 10:41 UTC, Pierre-Sassoulas approved these changes
I don't think we can use enumeration in the fragments, because it's already inside an enumeration. It's probably fixable but also not worth imo.

2023-03-09 10:51 UTC, merged