`pyreverse`: use colorblind friendly default colors
PyCQA/pylint pull request #8415
Opened 2023-03-09 17:55 UTC by DudeNr33

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description

As discussed in the issue, with 3.0 we can now change the default color palette.

Closes #8251

2023-03-09 18:13 UTC, Pierre-Sassoulas approved these changes
I did not review the graphical result... Code's LGTM :smile:

2023-03-09 18:14 UTC, DudeNr33 commented
For reference, this is how the new colors would look like:

![image](https://user-images.githubusercontent.com/3929834/224118198-90ce6f88-9076-418d-bd59-db6f0c09fa17.png)

2023-03-09 18:49 UTC, Pierre-Sassoulas commented
It looks fine with protanopia (no red) but it's a little hard with other form of colorblindness. 

No blue:

![tritanopia (no blue)](https://user-images.githubusercontent.com/5493666/224124361-f3ab0e73-4c3f-4f71-b49b-56371e899d72.png)

No coolor:
![achromatopia (no color at all)](https://user-images.githubusercontent.com/5493666/224124356-5a697d5e-c3a3-42c0-87da-b1681ee9bd05.png)

No green:
![deuteranopia (no green)](https://user-images.githubusercontent.com/5493666/224124359-9c1136ad-65e5-4b04-bd45-cd2a6f8d7468.png)

orange 2 and goldenrod 9 are not great in particular. This is not something that can be improvised. What were the color before that (maybe it's already taken into account by plantuml) ? Otherwise some research are in order I think :D

2023-03-09 20:13 UTC, DudeNr33 commented
Oh that's cool, what tool did you use to make the different versions? Or did you just desaturate it yourself?

I tried to adapt the [colorblind palette from seaborn](https://seaborn.pydata.org/tutorial/color_palettes.html#qualitative-color-palettes) with the closest matching HTML colors. 
But I will try to find something better. 👍

2023-03-09 20:30 UTC, Pierre-Sassoulas commented
It's firefox dev tools for accessibility (ctrl + shift + I), but there's probably the same thing in chrome. If it's already a colorblind palette then I don't think we're going to do much better than that, this is a hard problem to solve. They probably made the better result for red color blind because it's the most prevalent, it can't be perfect.

2023-03-09 21:40 UTC, DanielNoord commented
I am actually colorblind and these colours are indeed sub-optimal. Funilly enough the "no green" output Pierre gives works really well for my type of colour blindness but I don't know if it would work for others.

2023-03-09 22:00 UTC, Pierre-Sassoulas commented
I've found three possible color palettes:
IBM's : https://lospec.com/palette-list/ibm-color-blind-safe (It's IBM but there's only six of them)
Paul Tol's : https://personal.sron.nl/~pault/  (7, up to 10)
Ban wong: https://www.nature.com/articles/nmeth.1618 (8)

What's the best one in your opinion @DanielNoord ? Also do you know what type of color blindness you have ? It seems we should target red/green rather than blue/yellow, because red/green is a lot more common.

2023-03-09 22:11 UTC, DanielNoord commented
I have red/green, the second link works quite well for me!

2023-03-10 09:12 UTC, DanielNoord commented
> All figures in the second one, or a particular one ? :)

All are quite good, but figure 1 is definitely the best!

2023-03-10 09:58 UTC, Pierre-Sassoulas commented
I think we should use figure 7 then, there's 9 different values and the contrast with the black text is still high enough (compared to say the dark blue in figure 4 where there is more values but I can't read the value in it personally).

![fig7](https://user-images.githubusercontent.com/5493666/224285668-903a0f63-1338-461f-ad36-6053ac25495d.png)

Let me know if you want me to translate that in plantuml color @DudeNr33 :)

2023-03-10 10:07 UTC, Pierre-Sassoulas requested changes
(Colorblindness to take into account)

2023-03-10 18:19 UTC, DudeNr33 commented
I used the hex codes directly and made the `PlantUMLPrinter` work with both hex codes and CSS names.

Here is an example:
![image](https://user-images.githubusercontent.com/3929834/224390200-fdb29a87-5d67-4e5f-88e7-c4d7c18f9cda.png)

Updated the functional test file to make sure that both CSS names and HEX values can be given through the command line.

2023-03-10 18:43 UTC, Pierre-Sassoulas requested changes
Amazing we even got an enhancement for hexcode !

2023-03-10 18:43 UTC, Pierre-Sassoulas commented on pylint/pyreverse/main.py
> +    "#DDDDDD",  # pale greay
```suggestion
    "#DDDDDD",  # pale grey
```

2023-03-10 18:43 UTC, Pierre-Sassoulas commented on pylint/pyreverse/main.py
> +    "#77AADD",  # light blue
```suggestion
    # colorblind friendly palette taken from... (sorry I'm on mobile)
    "#77AADD",  # light blue
```

2023-03-10 18:49 UTC, DudeNr33 commented on pylint/pyreverse/main.py
> +    "#DDDDDD",  # pale greay
Oopsie

2023-03-10 18:53 UTC, Pierre-Sassoulas submitted a review, later dismissed
👌

2023-03-10 20:27 UTC, Pierre-Sassoulas approved these changes

2023-03-10 20:48 UTC, merged

2023-03-20 16:26 UTC, nickdrozd commented
I just saw the new colors -- they look great! :art: