Add some documentation examples
PyCQA/pylint pull request #8447
Opened 2023-03-13 19:09 UTC by DanielNoord

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

Refs https://github.com/PyCQA/pylint/issues/5953

2023-03-13 19:58 UTC, Pierre-Sassoulas requested changes

2023-03-17 07:51 UTC, DanielNoord commented on doc/data/messages/b/bad-file-encoding/good.py
> +    return "Success!"
I think it is nicer to show this as a file. I don't think the added lines matter too much.

2023-03-17 07:51 UTC, DanielNoord commented on doc/data/messages/r/return-arg-in-generator/good.py
> +def yield_numbers():
I think having an example is nice as it more explicit

2023-03-17 13:50 UTC, Pierre-Sassoulas commented on doc/data/messages/r/return-arg-in-generator/good.py
> +def yield_numbers():
Yes, it's nice having an example even for deleted messages (for user of older versions in particular).

2023-03-20 08:26 UTC, Pierre-Sassoulas approved these changes

2023-03-20 09:48 UTC, merged