[test multiprocessing] Fix tests for unpickable plugins
PyCQA/pylint pull request #8470
Opened 2023-03-20 22:44 UTC by Pierre-Sassoulas

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

It was fixed previously I don't know when.

2023-03-20 22:46 UTC, DanielNoord requested changes
This was fixed because of removing deprecated code.

Ideally we would keep this test as it is a good regression test against removing `dill` (or checking if we actually can).

2023-03-20 23:35 UTC, DanielNoord reviewed
You didn't need to change anything and this worked again?

2023-03-21 06:33 UTC, Pierre-Sassoulas commented
Pretty much !

2023-03-21 06:46 UTC, DanielNoord approved these changes

2023-03-21 06:54 UTC, merged