allow-global-unused-variables should respect dummy-variables-rgx
PyCQA/pylint pull request #9570
Opened 2024-04-25 16:38 UTC by com6056

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Refs #XXXX

Closes #XXXX

2024-04-26 15:25 UTC, com6056 commented
Not sure if this change requires news or not, let me know if it does though! I just don't have all the tools installed to regenerate everything but can get that going if needed.

2024-04-29 07:45 UTC, DanielNoord commented
This would indeed require a news entry, if you don't want to install the tools you can probably copy one from a previous PR and see what the syntax looks like there.

2024-04-29 17:34 UTC, com6056 commented
> This would indeed require a news entry, if you don't want to install the tools you can probably copy one from a previous PR and see what the syntax looks like there.

Done! Just peeked at some other PRs, took a few tries but seems like it is happy now haha, let me know if there's anything else needed before we can get this merged in! 🎉

2024-04-29 21:39 UTC, Pierre-Sassoulas requested changes
Thank you for opening a PR. I do think we need to think about #8013 before "fixing" this. There's a bad/ "two options in parallel" initial design and we need to restore consistency (and document this better then close #8013 in this MR, if this MR restore consistency).

2024-04-29 22:50 UTC, com6056 commented
> Thank you for opening a PR. I do think we need to think about #8013 before "fixing" this. There's a bad/ "two options in parallel" initial design and we need to restore consistency (and document this better then close #8013 in this MR, if this MR restore consistency).

Any idea how long this will take? Could I instead just add a new flag that allows you instead to opt-in to this behavior then if it might take a while to resolve #8013?

2024-04-30 09:30 UTC, Pierre-Sassoulas commented
If you can propose a consistent design it could be fast, otherwise we need to wait for someone else to think this is important and volunteer to think about it. Maybe the current MR is enough and making them mutually exclusive and using only one option at a time is not the way to go. But it should be argumented/documented. Right now I feel we're fixing a particular use case, instead of actually fixing the root issue and are going to throw all this when actually looking into it.

2024-05-03 18:18 UTC, com6056 commented
Where in the docs should I add this? And what do you mean by `argumented`? Should I add another CLI flag that enables this?

2024-05-03 20:18 UTC, Pierre-Sassoulas commented
> And what do you mean by "argumented"? Should I add another CLI flag that enables this?

Sorry I was thinking in french, I actually meant argued / reasoned that the better solution is to keep both options and not make them mutually exclusive. We would need to document both of the options if that's the case (here https://github.com/pylint-dev/pylint/blob/3c8be8ee40babf9bcbaae53b9f2ec518c6d76ca7/pylint/checkers/variables.py#L1243).

2026-04-19 04:59 UTC, closed without merging