Add clarification of the r string modifier
PyCQA/pylint pull request #9571
Opened 2024-04-26 09:33 UTC by tedsecretsource

Raw sting literals may not be easily understood based on the brief description. This description is much more verbose (maybe too verbose) but should help the novice python programmer understand what the r modifier is and how / when to use it.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

Added a more verbose description of the r (raw string literal) modifier for the novices like me…

2024-04-28 19:01 UTC, Pierre-Sassoulas requested changes
Thank you for contributing to pylint and for making the doc better. I feel like this is way too verbose, It should be a sentence for each solution, maybe in a comment in the "good" example. We can add a link to a very detailed tutorial in "related.rst" however.

2024-05-23 11:21 UTC, tedsecretsource commented
Hi @Pierre-Sassoulas. Thanks for the feedback. I am brand new to this project so not sure how to add the link to related.rst. If you can provide an example, I'll give this another try.

My intention with this PR is to try and clarify, or encourage, the use of the `r` string modifier because, I believe, it probably should be used in the majority of cases.

How about this: `Use raw string literals (prefix with 'r') or double backslashes (\\) in Python to avoid escape sequence issues in regex. Example: r"\." or "\\." for a literal dot character.`

To me it's only barely better.

@UlrichEckhardt Excellent feedback. Thank you. Let's see if we can get the initial sentence right and then add details to related.rst

Looking forward to your replies.

2024-06-03 20:29 UTC, DanielNoord commented
I agree that this is a bit too verbose for our documentation. We're not trying to explain all of Python, there are excellent resources for that on the internet.

2024-06-04 07:18 UTC, Pierre-Sassoulas commented
>  not sure how to add the link to related.rst. 

Hey, you can create a file called "doc/data/messages/a/anomalous-backslash-in-string/related.rst", look at other related.rst in the repo for examples :)

2026-04-27 09:22 UTC, closed without merging